package com.jfinal.weixin.models;

import com.jfinal.weixin.base.BaseAbRecv;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class AbRecv extends BaseAbRecv<AbRecv> {
	public static final AbRecv dao = new AbRecv();
}
