package com.jfinal.weixin.models;

import com.jfinal.weixin.base.BaseAbSend;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class AbSend extends BaseAbSend<AbSend> {
	public static final AbSend dao = new AbSend();
}
