package com.jfinal.weixin.models;

import com.jfinal.weixin.base.BaseAndroidtrackdouble;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Androidtrackdouble extends BaseAndroidtrackdouble<Androidtrackdouble> {
	public static final Androidtrackdouble dao = new Androidtrackdouble();
}
