package com.jfinal.weixin.models;

import com.jfinal.weixin.base.BaseAndroidcabinetb;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Androidcabinetb extends BaseAndroidcabinetb<Androidcabinetb> {
	public static final Androidcabinetb dao = new Androidcabinetb();
}
