package com.jfinal.weixin.models;

import com.jfinal.weixin.base.BaseAndroidcabinete;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Androidcabinete extends BaseAndroidcabinete<Androidcabinete> {
	public static final Androidcabinete dao = new Androidcabinete();
}
