package com.jfinal.weixin.models;

import com.jfinal.weixin.base.BaseAndroidnetinfo;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Androidnetinfo extends BaseAndroidnetinfo<Androidnetinfo> {
	public static final Androidnetinfo dao = new Androidnetinfo();
}
