package com.jfinal.weixin.models;

import com.jfinal.weixin.base.BaseAndroidrouteplan;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Androidrouteplan extends BaseAndroidrouteplan<Androidrouteplan> {
	public static final Androidrouteplan dao = new Androidrouteplan();
}
