package com.jfinal.weixin.models;

import com.jfinal.weixin.base.BaseAndroidroute;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Androidroute extends BaseAndroidroute<Androidroute> {
	public static final Androidroute dao = new Androidroute();
}
