package com.jfinal.weixin.models;

import com.jfinal.weixin.base.BaseAndroidsalelist;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Androidsalelist extends BaseAndroidsalelist<Androidsalelist> {
	public static final Androidsalelist dao = new Androidsalelist();
}
