package com.jfinal.weixin.models;

import com.jfinal.weixin.base.BaseAndroidnetappstartLog;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class AndroidnetappstartLog extends BaseAndroidnetappstartLog<AndroidnetappstartLog> {
	public static final AndroidnetappstartLog dao = new AndroidnetappstartLog();
}
