package com.jfinal.weixin.models;

import com.jfinal.weixin.base.BaseAndroidnetappstart;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Androidnetappstart extends BaseAndroidnetappstart<Androidnetappstart> {
	public static final Androidnetappstart dao = new Androidnetappstart();
}
