package com.jfinal.weixin.models;

import com.jfinal.weixin.base.BaseAndroidtrackka;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Androidtrackka extends BaseAndroidtrackka<Androidtrackka> {
	public static final Androidtrackka dao = new Androidtrackka();
}
