package com.jfinal.weixin.models;

import com.jfinal.weixin.base.BaseAndroidcabineta;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Androidcabineta extends BaseAndroidcabineta<Androidcabineta> {
	public static final Androidcabineta dao = new Androidcabineta();
}
