package com.jfinal.weixin.models;

import com.jfinal.weixin.base.BaseAndroidsalelistHistory;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class AndroidsalelistHistory extends BaseAndroidsalelistHistory<AndroidsalelistHistory> {
	public static final AndroidsalelistHistory dao = new AndroidsalelistHistory();
}
