package com.jfinal.weixin.models;

import com.jfinal.weixin.base.BaseAndroidsetpara;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Androidsetpara extends BaseAndroidsetpara<Androidsetpara> {
	public static final Androidsetpara dao = new Androidsetpara();
}
