package com.jfinal.weixin.models;

import com.jfinal.weixin.base.BaseAndroidcabinetd;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Androidcabinetd extends BaseAndroidcabinetd<Androidcabinetd> {
	public static final Androidcabinetd dao = new Androidcabinetd();
}
