package com.jfinal.weixin.models;

import com.jfinal.weixin.base.BaseAndroidguangone;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Androidguangone extends BaseAndroidguangone<Androidguangone> {
	public static final Androidguangone dao = new Androidguangone();
}
