package com.jfinal.weixin.models;

import com.jfinal.weixin.base.BaseAndroidvmuserinfo;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Androidvmuserinfo extends BaseAndroidvmuserinfo<Androidvmuserinfo> {
	public static final Androidvmuserinfo dao = new Androidvmuserinfo();
}
