package com.jfinal.weixin.models;

import com.jfinal.weixin.base.BaseAndroiderrorpwdLog;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class AndroiderrorpwdLog extends BaseAndroiderrorpwdLog<AndroiderrorpwdLog> {
	public static final AndroiderrorpwdLog dao = new AndroiderrorpwdLog();
}
