package com.jfinal.weixin.models;

import com.jfinal.weixin.base.BaseAndroidcoffee;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Androidcoffee extends BaseAndroidcoffee<Androidcoffee> {
	public static final Androidcoffee dao = new Androidcoffee();
}
