package com.jfinal.weixin.models;

import com.jfinal.weixin.base.BaseAndroidcabinetc;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Androidcabinetc extends BaseAndroidcabinetc<Androidcabinetc> {
	public static final Androidcabinetc dao = new Androidcabinetc();
}
