package com.jfinal.weixin.models;

import com.jfinal.weixin.base.BaseAppCoupon;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class AppCoupon extends BaseAppCoupon<AppCoupon> {
	public static final AppCoupon dao = new AppCoupon();
}
