package com.jfinal.weixin.models;

import com.jfinal.weixin.base.BaseAppGoodsurl;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class AppGoodsurl extends BaseAppGoodsurl<AppGoodsurl> {
	public static final AppGoodsurl dao = new AppGoodsurl();
}
