package com.jfinal.weixin.models;

import com.jfinal.weixin.base.BaseAppLastestversion;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class AppLastestversion extends BaseAppLastestversion<AppLastestversion> {
	public static final AppLastestversion dao = new AppLastestversion();
}
