package com.jfinal.weixin.models;

import com.jfinal.weixin.base.BaseAppMobilechkcode;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class AppMobilechkcode extends BaseAppMobilechkcode<AppMobilechkcode> {
	public static final AppMobilechkcode dao = new AppMobilechkcode();
}
