package com.jfinal.weixin.models;

import com.jfinal.weixin.base.BaseAppOperater;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class AppOperater extends BaseAppOperater<AppOperater> {
	public static final AppOperater dao = new AppOperater();
}
