package com.jfinal.weixin.models;

import com.jfinal.weixin.base.BaseAppPpn;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class AppPpn extends BaseAppPpn<AppPpn> {
	public static final AppPpn dao = new AppPpn();
}
