package com.jfinal.weixin.models;

import com.jfinal.weixin.base.BaseAppPointruler;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class AppPointruler extends BaseAppPointruler<AppPointruler> {
	public static final AppPointruler dao = new AppPointruler();
}
