package com.jfinal.weixin.models;

import com.jfinal.weixin.base.BaseAppPointexchange;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class AppPointexchange extends BaseAppPointexchange<AppPointexchange> {
	public static final AppPointexchange dao = new AppPointexchange();
}
