package com.jfinal.weixin.models;

import com.jfinal.weixin.base.BaseAppUserppn;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class AppUserppn extends BaseAppUserppn<AppUserppn> {
	public static final AppUserppn dao = new AppUserppn();
}
