package com.jfinal.weixin.models;

import com.jfinal.weixin.base.BaseAppUserpayok;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class AppUserpayok extends BaseAppUserpayok<AppUserpayok> {
	public static final AppUserpayok dao = new AppUserpayok();
}
