package com.jfinal.weixin.models;

import com.jfinal.weixin.base.BaseAppUserpointexrecord;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class AppUserpointexrecord extends BaseAppUserpointexrecord<AppUserpointexrecord> {
	public static final AppUserpointexrecord dao = new AppUserpointexrecord();
}
