package com.jfinal.weixin.models;

import com.jfinal.weixin.base.BaseAppUserinfo;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class AppUserinfo extends BaseAppUserinfo<AppUserinfo> {
	public static final AppUserinfo dao = new AppUserinfo();
}
