package com.jfinal.weixin.models;

import com.jfinal.weixin.base.BaseAppUsermoneyrecord;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class AppUsermoneyrecord extends BaseAppUsermoneyrecord<AppUsermoneyrecord> {
	public static final AppUsermoneyrecord dao = new AppUsermoneyrecord();
}
