package com.jfinal.weixin.models;

import com.jfinal.weixin.base.BaseAppUsershareppn;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class AppUsershareppn extends BaseAppUsershareppn<AppUsershareppn> {
	public static final AppUsershareppn dao = new AppUsershareppn();
}
