package com.jfinal.weixin.models;

import com.jfinal.weixin.base.BaseAppUsercoupon;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class AppUsercoupon extends BaseAppUsercoupon<AppUsercoupon> {
	public static final AppUsercoupon dao = new AppUsercoupon();
}
