package com.jfinal.weixin.models;

import com.jfinal.weixin.base.BaseAppUserpayback;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class AppUserpayback extends BaseAppUserpayback<AppUserpayback> {
	public static final AppUserpayback dao = new AppUserpayback();
}
