package com.jfinal.weixin.models;

import com.jfinal.weixin.base.BaseAppUseradvice;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class AppUseradvice extends BaseAppUseradvice<AppUseradvice> {
	public static final AppUseradvice dao = new AppUseradvice();
}
