package com.jfinal.weixin.models;

import com.jfinal.weixin.base.BaseAppUserbbs;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class AppUserbbs extends BaseAppUserbbs<AppUserbbs> {
	public static final AppUserbbs dao = new AppUserbbs();
}
