package com.jfinal.weixin.models;

import com.jfinal.weixin.base.BaseAppUserpointrecord;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class AppUserpointrecord extends BaseAppUserpointrecord<AppUserpointrecord> {
	public static final AppUserpointrecord dao = new AppUserpointrecord();
}
