package com.jfinal.weixin.models;

import com.jfinal.weixin.base.BaseAppUserbuygoods;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class AppUserbuygoods extends BaseAppUserbuygoods<AppUserbuygoods> {
	public static final AppUserbuygoods dao = new AppUserbuygoods();
}
