package com.jfinal.weixin.models;

import com.jfinal.weixin.base.BaseChenmonth;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Chenmonth extends BaseChenmonth<Chenmonth> {
	public static final Chenmonth dao = new Chenmonth();
}
