package com.jfinal.weixin.models;

import com.jfinal.weixin.base.BaseGoodsname206;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Goodsname206 extends BaseGoodsname206<Goodsname206> {
	public static final Goodsname206 dao = new Goodsname206();
}
