package com.jfinal.weixin.models;

import com.jfinal.weixin.base.BaseGoodsname;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Goodsname extends BaseGoodsname<Goodsname> {
	public static final Goodsname dao = new Goodsname();
}
