package com.jfinal.weixin.models;

import com.jfinal.weixin.base.BaseGoodsnameav;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Goodsnameav extends BaseGoodsnameav<Goodsnameav> {
	public static final Goodsnameav dao = new Goodsnameav();
}
