package com.jfinal.weixin.models;

import com.jfinal.weixin.base.BaseHzcityblack;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Hzcityblack extends BaseHzcityblack<Hzcityblack> {
	public static final Hzcityblack dao = new Hzcityblack();
}
