package com.jfinal.weixin.models;

import com.jfinal.weixin.base.BaseHzcityrecord;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Hzcityrecord extends BaseHzcityrecord<Hzcityrecord> {
	public static final Hzcityrecord dao = new Hzcityrecord();
}
