package com.jfinal.weixin.models;

import com.jfinal.weixin.base.BaseHzcityyyyymmdd;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Hzcityyyyymmdd extends BaseHzcityyyyymmdd<Hzcityyyyymmdd> {
	public static final Hzcityyyyymmdd dao = new Hzcityyyyymmdd();
}
