package com.jfinal.weixin.models;

import com.jfinal.weixin.base.BaseIdVmrechargeunit;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class IdVmrechargeunit extends BaseIdVmrechargeunit<IdVmrechargeunit> {
	public static final IdVmrechargeunit dao = new IdVmrechargeunit();
}
