package com.jfinal.weixin.models;

import com.jfinal.weixin.base.BaseIdVmoperatecard;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class IdVmoperatecard extends BaseIdVmoperatecard<IdVmoperatecard> {
	public static final IdVmoperatecard dao = new IdVmoperatecard();
}
