package com.jfinal.weixin.models;

import com.jfinal.weixin.base.BaseIdVmunitrecord;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class IdVmunitrecord extends BaseIdVmunitrecord<IdVmunitrecord> {
	public static final IdVmunitrecord dao = new IdVmunitrecord();
}
