package com.jfinal.weixin.models;

import com.jfinal.weixin.base.BaseIdVmunit;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class IdVmunit extends BaseIdVmunit<IdVmunit> {
	public static final IdVmunit dao = new IdVmunit();
}
