package com.jfinal.weixin.models;

import com.jfinal.weixin.base.BaseIdVmrechargecard;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class IdVmrechargecard extends BaseIdVmrechargecard<IdVmrechargecard> {
	public static final IdVmrechargecard dao = new IdVmrechargecard();
}
