package com.jfinal.weixin.models;

import com.jfinal.weixin.base.BaseIdVmexpenserecord;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class IdVmexpenserecord extends BaseIdVmexpenserecord<IdVmexpenserecord> {
	public static final IdVmexpenserecord dao = new IdVmexpenserecord();
}
