package com.jfinal.weixin.models;

import com.jfinal.weixin.base.BaseIdVmcards;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class IdVmcards extends BaseIdVmcards<IdVmcards> {
	public static final IdVmcards dao = new IdVmcards();
}
