package com.jfinal.weixin.models;

import com.jfinal.weixin.base.BaseIdVmunitoperator;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class IdVmunitoperator extends BaseIdVmunitoperator<IdVmunitoperator> {
	public static final IdVmunitoperator dao = new IdVmunitoperator();
}
