package com.jfinal.weixin.models;

import com.jfinal.weixin.base.BaseLatestappversion;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Latestappversion extends BaseLatestappversion<Latestappversion> {
	public static final Latestappversion dao = new Latestappversion();
}
