package com.jfinal.weixin.models;

import com.jfinal.weixin.base.BaseModuleMst;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ModuleMst extends BaseModuleMst<ModuleMst> {
	public static final ModuleMst dao = new ModuleMst();
}
