package com.jfinal.weixin.models;

import com.jfinal.weixin.base.BasePayokHistory;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class PayokHistory extends BasePayokHistory<PayokHistory> {
	public static final PayokHistory dao = new PayokHistory();
}
