package com.jfinal.weixin.models;

import com.jfinal.weixin.base.BasePayok;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Payok extends BasePayok<Payok> {
	public static final Payok dao = new Payok();
}
