package com.jfinal.weixin.models;

import com.jfinal.weixin.base.BasePayowner;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Payowner extends BasePayowner<Payowner> {
	public static final Payowner dao = new Payowner();
}
