package com.jfinal.weixin.models;

import com.jfinal.weixin.base.BaseRoleMst;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class RoleMst extends BaseRoleMst<RoleMst> {
	public static final RoleMst dao = new RoleMst();
}
