package com.jfinal.weixin.models;

import com.jfinal.weixin.base.BaseRolePermMst;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class RolePermMst extends BaseRolePermMst<RolePermMst> {
	public static final RolePermMst dao = new RolePermMst();
}
