package com.jfinal.weixin.models;

import com.jfinal.weixin.base.BaseSaleNowmm;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SaleNowmm extends BaseSaleNowmm<SaleNowmm> {
	public static final SaleNowmm dao = new SaleNowmm();
}
