package com.jfinal.weixin.models;

import com.jfinal.weixin.base.BaseSaleYesterday;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SaleYesterday extends BaseSaleYesterday<SaleYesterday> {
	public static final SaleYesterday dao = new SaleYesterday();
}
