package com.jfinal.weixin.models;

import com.jfinal.weixin.base.BaseSaleLastmm;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SaleLastmm extends BaseSaleLastmm<SaleLastmm> {
	public static final SaleLastmm dao = new SaleLastmm();
}
