package com.jfinal.weixin.models;

import com.jfinal.weixin.base.BaseSupply206;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Supply206 extends BaseSupply206<Supply206> {
	public static final Supply206 dao = new Supply206();
}
