package com.jfinal.weixin.models;

import com.jfinal.weixin.base.BaseSysUserRoleMst;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SysUserRoleMst extends BaseSysUserRoleMst<SysUserRoleMst> {
	public static final SysUserRoleMst dao = new SysUserRoleMst();
}
