package com.jfinal.weixin.models;

import com.jfinal.weixin.base.BaseViewTodaySale;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ViewTodaySale extends BaseViewTodaySale<ViewTodaySale> {
	public static final ViewTodaySale dao = new ViewTodaySale();
}
