package com.jfinal.weixin.models;

import com.jfinal.weixin.base.BaseViewYyyymmSale;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ViewYyyymmSale extends BaseViewYyyymmSale<ViewYyyymmSale> {
	public static final ViewYyyymmSale dao = new ViewYyyymmSale();
}
