package com.jfinal.weixin.models;

import com.jfinal.weixin.base.BaseViewVmexpenserecord;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ViewVmexpenserecord extends BaseViewVmexpenserecord<ViewVmexpenserecord> {
	public static final ViewVmexpenserecord dao = new ViewVmexpenserecord();
}
