package com.jfinal.weixin.models;

import com.jfinal.weixin.base.BaseViewYesterdaySale;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ViewYesterdaySale extends BaseViewYesterdaySale<ViewYesterdaySale> {
	public static final ViewYesterdaySale dao = new ViewYesterdaySale();
}
