package com.jfinal.weixin.models;

import com.jfinal.weixin.base.BaseViewAndroidnetappstartLogLast;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ViewAndroidnetappstartLogLast extends BaseViewAndroidnetappstartLogLast<ViewAndroidnetappstartLogLast> {
	public static final ViewAndroidnetappstartLogLast dao = new ViewAndroidnetappstartLogLast();
}
