package com.jfinal.weixin.models;

import com.jfinal.weixin.base.BaseViewNowmmSale;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ViewNowmmSale extends BaseViewNowmmSale<ViewNowmmSale> {
	public static final ViewNowmmSale dao = new ViewNowmmSale();
}
