package com.jfinal.weixin.models;

import com.jfinal.weixin.base.BaseViewYyyymmddSale;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ViewYyyymmddSale extends BaseViewYyyymmddSale<ViewYyyymmddSale> {
	public static final ViewYyyymmddSale dao = new ViewYyyymmddSale();
}
