package com.jfinal.weixin.models;

import com.jfinal.weixin.base.BaseViewAndroidnetappstartLogLastInfo;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ViewAndroidnetappstartLogLastInfo extends BaseViewAndroidnetappstartLogLastInfo<ViewAndroidnetappstartLogLastInfo> {
	public static final ViewAndroidnetappstartLogLastInfo dao = new ViewAndroidnetappstartLogLastInfo();
}
