package com.jfinal.weixin.models;

import com.jfinal.weixin.base.BaseViewLastmmSale;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ViewLastmmSale extends BaseViewLastmmSale<ViewLastmmSale> {
	public static final ViewLastmmSale dao = new ViewLastmmSale();
}
