package com.jfinal.weixin.models;

import com.jfinal.weixin.base.BaseVmcustomerinfo;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Vmcustomerinfo extends BaseVmcustomerinfo<Vmcustomerinfo> {
	public static final Vmcustomerinfo dao = new Vmcustomerinfo();
}
