package com.jfinal.weixin.models;

import com.jfinal.weixin.base.BaseVmcustomerproxy;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Vmcustomerproxy extends BaseVmcustomerproxy<Vmcustomerproxy> {
	public static final Vmcustomerproxy dao = new Vmcustomerproxy();
}
