package com.jfinal.weixin.models;

import com.jfinal.weixin.base.BaseVmmisuserLog;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class VmmisuserLog extends BaseVmmisuserLog<VmmisuserLog> {
	public static final VmmisuserLog dao = new VmmisuserLog();
}
