package com.jfinal.weixin.models;

import com.jfinal.weixin.base.BaseVmmisuser;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Vmmisuser extends BaseVmmisuser<Vmmisuser> {
	public static final Vmmisuser dao = new Vmmisuser();
}
