package com.jfinal.weixin.models;

import com.jfinal.weixin.base.BaseVmmisuserpara;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Vmmisuserpara extends BaseVmmisuserpara<Vmmisuserpara> {
	public static final Vmmisuserpara dao = new Vmmisuserpara();
}
