package com.jfinal.weixin.models;

import com.jfinal.weixin.base.BaseWxFaninfo;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class WxFaninfo extends BaseWxFaninfo<WxFaninfo> {
	public static final WxFaninfo dao = new WxFaninfo();
}
