package com.jfinal.weixin.models;

import com.jfinal.weixin.base.BaseWxidOpenidCardno;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class WxidOpenidCardno extends BaseWxidOpenidCardno<WxidOpenidCardno> {
	public static final WxidOpenidCardno dao = new WxidOpenidCardno();
}
