package com.jfinal.weixin.models;

import com.jfinal.weixin.base.BaseWxidChargeCardno;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class WxidChargeCardno extends BaseWxidChargeCardno<WxidChargeCardno> {
	public static final WxidChargeCardno dao = new WxidChargeCardno();
}
