package com.jfinal.weixin.models;

import com.jfinal.weixin.base.BaseWxidVmidWxopenid;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class WxidVmidWxopenid extends BaseWxidVmidWxopenid<WxidVmidWxopenid> {
	public static final WxidVmidWxopenid dao = new WxidVmidWxopenid();
}
