package com.jfinal.weixin.models;

import com.jfinal.weixin.base.BaseWxidStock;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class WxidStock extends BaseWxidStock<WxidStock> {
	public static final WxidStock dao = new WxidStock();
}
