package com.jfinal.weixin.models;

import com.jfinal.weixin.base.BaseWxOwnerinfo;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class WxOwnerinfo extends BaseWxOwnerinfo<WxOwnerinfo> {
	public static final WxOwnerinfo dao = new WxOwnerinfo();
}
