package com.jfinal.weixin.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseAndroidrouteplan<M extends BaseAndroidrouteplan<M>> extends Model<M> implements IBean {

	public void setMasterid(java.lang.Long masterid) {
		set("masterid", masterid);
	}

	public java.lang.Long getMasterid() {
		return get("masterid");
	}

	public void setSlaveid(java.lang.Long slaveid) {
		set("slaveid", slaveid);
	}

	public java.lang.Long getSlaveid() {
		return get("slaveid");
	}

}
