package com.jfinal.weixin.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseAppUserbuygoods<M extends BaseAppUserbuygoods<M>> extends Model<M> implements IBean {

	public void setBuyorderid(java.math.BigInteger buyorderid) {
		set("buyorderid", buyorderid);
	}

	public java.math.BigInteger getBuyorderid() {
		return get("buyorderid");
	}

	public void setBuydate(java.util.Date buydate) {
		set("buydate", buydate);
	}

	public java.util.Date getBuydate() {
		return get("buydate");
	}

	public void setBuytime(java.util.Date buytime) {
		set("buytime", buytime);
	}

	public java.util.Date getBuytime() {
		return get("buytime");
	}

	public void setBuyorderstatus(java.lang.String buyorderstatus) {
		set("buyorderstatus", buyorderstatus);
	}

	public java.lang.String getBuyorderstatus() {
		return get("buyorderstatus");
	}

	public void setExchangecode(java.lang.String exchangecode) {
		set("exchangecode", exchangecode);
	}

	public java.lang.String getExchangecode() {
		return get("exchangecode");
	}

	public void setBuyuserid(java.lang.Long buyuserid) {
		set("buyuserid", buyuserid);
	}

	public java.lang.Long getBuyuserid() {
		return get("buyuserid");
	}

	public void setBuyway(java.lang.String buyway) {
		set("buyway", buyway);
	}

	public java.lang.String getBuyway() {
		return get("buyway");
	}

	public void setCouponid(java.lang.Long couponid) {
		set("couponid", couponid);
	}

	public java.lang.Long getCouponid() {
		return get("couponid");
	}

	public void setPayway(java.lang.String payway) {
		set("payway", payway);
	}

	public java.lang.String getPayway() {
		return get("payway");
	}

	public void setPaytransid(java.lang.String paytransid) {
		set("paytransid", paytransid);
	}

	public java.lang.String getPaytransid() {
		return get("paytransid");
	}

	public void setPaymoney(java.math.BigDecimal paymoney) {
		set("paymoney", paymoney);
	}

	public java.math.BigDecimal getPaymoney() {
		return get("paymoney");
	}

	public void setPayerid(java.lang.String payerid) {
		set("payerid", payerid);
	}

	public java.lang.String getPayerid() {
		return get("payerid");
	}

	public void setUsedwalletmoney(java.math.BigDecimal usedwalletmoney) {
		set("usedwalletmoney", usedwalletmoney);
	}

	public java.math.BigDecimal getUsedwalletmoney() {
		return get("usedwalletmoney");
	}

	public void setGoodautoid(java.lang.Long goodautoid) {
		set("goodautoid", goodautoid);
	}

	public java.lang.Long getGoodautoid() {
		return get("goodautoid");
	}

	public void setGoodname(java.lang.String goodname) {
		set("goodname", goodname);
	}

	public java.lang.String getGoodname() {
		return get("goodname");
	}

	public void setGoodcashprice(java.math.BigDecimal goodcashprice) {
		set("goodcashprice", goodcashprice);
	}

	public java.math.BigDecimal getGoodcashprice() {
		return get("goodcashprice");
	}

	public void setGoodappprice(java.math.BigDecimal goodappprice) {
		set("goodappprice", goodappprice);
	}

	public java.math.BigDecimal getGoodappprice() {
		return get("goodappprice");
	}

	public void setOrdervmcode(java.lang.String ordervmcode) {
		set("ordervmcode", ordervmcode);
	}

	public java.lang.String getOrdervmcode() {
		return get("ordervmcode");
	}

	public void setOrdervmname(java.lang.String ordervmname) {
		set("ordervmname", ordervmname);
	}

	public java.lang.String getOrdervmname() {
		return get("ordervmname");
	}

	public void setOrdervmaddress(java.lang.String ordervmaddress) {
		set("ordervmaddress", ordervmaddress);
	}

	public java.lang.String getOrdervmaddress() {
		return get("ordervmaddress");
	}

	public void setOutvmcode(java.lang.String outvmcode) {
		set("outvmcode", outvmcode);
	}

	public java.lang.String getOutvmcode() {
		return get("outvmcode");
	}

	public void setOutvmname(java.lang.String outvmname) {
		set("outvmname", outvmname);
	}

	public java.lang.String getOutvmname() {
		return get("outvmname");
	}

	public void setOutvmaddress(java.lang.String outvmaddress) {
		set("outvmaddress", outvmaddress);
	}

	public java.lang.String getOutvmaddress() {
		return get("outvmaddress");
	}

	public void setOutway(java.lang.String outway) {
		set("outway", outway);
	}

	public java.lang.String getOutway() {
		return get("outway");
	}

	public void setUpdatetime(java.util.Date updatetime) {
		set("updatetime", updatetime);
	}

	public java.util.Date getUpdatetime() {
		return get("updatetime");
	}

	public void setOuttransid(java.lang.String outtransid) {
		set("outtransid", outtransid);
	}

	public java.lang.String getOuttransid() {
		return get("outtransid");
	}

}
