package com.jfinal.weixin.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseAppUsershareppn<M extends BaseAppUsershareppn<M>> extends Model<M> implements IBean {

	public void setUserid(java.lang.Long userid) {
		set("userid", userid);
	}

	public java.lang.Long getUserid() {
		return get("userid");
	}

	public void setPpnid(java.lang.Long ppnid) {
		set("ppnid", ppnid);
	}

	public java.lang.Long getPpnid() {
		return get("ppnid");
	}

	public void setSharerouter(java.lang.String sharerouter) {
		set("sharerouter", sharerouter);
	}

	public java.lang.String getSharerouter() {
		return get("sharerouter");
	}

	public void setShareuserid(java.lang.String shareuserid) {
		set("shareuserid", shareuserid);
	}

	public java.lang.String getShareuserid() {
		return get("shareuserid");
	}

	public void setFirstsharetime(java.util.Date firstsharetime) {
		set("firstsharetime", firstsharetime);
	}

	public java.util.Date getFirstsharetime() {
		return get("firstsharetime");
	}

	public void setFirstsharepoint(java.lang.Integer firstsharepoint) {
		set("firstsharepoint", firstsharepoint);
	}

	public java.lang.Integer getFirstsharepoint() {
		return get("firstsharepoint");
	}

	public void setTotalsharecount(java.lang.Integer totalsharecount) {
		set("totalsharecount", totalsharecount);
	}

	public java.lang.Integer getTotalsharecount() {
		return get("totalsharecount");
	}

	public void setLastsharetime(java.util.Date lastsharetime) {
		set("lastsharetime", lastsharetime);
	}

	public java.util.Date getLastsharetime() {
		return get("lastsharetime");
	}

}
