package com.jfinal.weixin.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseAppUserbbs<M extends BaseAppUserbbs<M>> extends Model<M> implements IBean {

	public void setBbsid(java.math.BigInteger bbsid) {
		set("bbsid", bbsid);
	}

	public java.math.BigInteger getBbsid() {
		return get("bbsid");
	}

	public void setUserid(java.lang.Long userid) {
		set("userid", userid);
	}

	public java.lang.Long getUserid() {
		return get("userid");
	}

	public void setPpnid(java.lang.Long ppnid) {
		set("ppnid", ppnid);
	}

	public java.lang.Long getPpnid() {
		return get("ppnid");
	}

	public void setBbsinserttime(java.util.Date bbsinserttime) {
		set("bbsinserttime", bbsinserttime);
	}

	public java.util.Date getBbsinserttime() {
		return get("bbsinserttime");
	}

	public void setBbstext(java.lang.String bbstext) {
		set("bbstext", bbstext);
	}

	public java.lang.String getBbstext() {
		return get("bbstext");
	}

	public void setAddpoint(java.lang.Integer addpoint) {
		set("addpoint", addpoint);
	}

	public java.lang.Integer getAddpoint() {
		return get("addpoint");
	}

	public void setIllegal(java.lang.Integer illegal) {
		set("illegal", illegal);
	}

	public java.lang.Integer getIllegal() {
		return get("illegal");
	}

	public void setSubpoint(java.lang.Integer subpoint) {
		set("subpoint", subpoint);
	}

	public java.lang.Integer getSubpoint() {
		return get("subpoint");
	}

	public void setOperatename(java.lang.String operatename) {
		set("operatename", operatename);
	}

	public java.lang.String getOperatename() {
		return get("operatename");
	}

	public void setOperatetime(java.util.Date operatetime) {
		set("operatetime", operatetime);
	}

	public java.util.Date getOperatetime() {
		return get("operatetime");
	}

}
