package com.jfinal.weixin.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseRoleMst<M extends BaseRoleMst<M>> extends Model<M> implements IBean {

	public void setIdRole(java.math.BigInteger idRole) {
		set("id_role", idRole);
	}

	public java.math.BigInteger getIdRole() {
		return get("id_role");
	}

	public void setRoleName(java.lang.String roleName) {
		set("role_name", roleName);
	}

	public java.lang.String getRoleName() {
		return get("role_name");
	}

	public void setFlgDeleted(java.lang.Integer flgDeleted) {
		set("flg_deleted", flgDeleted);
	}

	public java.lang.Integer getFlgDeleted() {
		return get("flg_deleted");
	}

	public void setIdCrtUser(java.math.BigInteger idCrtUser) {
		set("id_crt_user", idCrtUser);
	}

	public java.math.BigInteger getIdCrtUser() {
		return get("id_crt_user");
	}

	public void setTimeCrt(java.util.Date timeCrt) {
		set("time_crt", timeCrt);
	}

	public java.util.Date getTimeCrt() {
		return get("time_crt");
	}

	public void setIdUpdUser(java.math.BigInteger idUpdUser) {
		set("id_upd_user", idUpdUser);
	}

	public java.math.BigInteger getIdUpdUser() {
		return get("id_upd_user");
	}

	public void setTimeUpd(java.util.Date timeUpd) {
		set("time_upd", timeUpd);
	}

	public java.util.Date getTimeUpd() {
		return get("time_upd");
	}

}
