package com.jfinal.weixin.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseGoodsnameav<M extends BaseGoodsnameav<M>> extends Model<M> implements IBean {

	public void setGoodautoid(java.lang.Long goodautoid) {
		set("goodautoid", goodautoid);
	}

	public java.lang.Long getGoodautoid() {
		return get("goodautoid");
	}

	public void setVmcustomerid(java.lang.Long vmcustomerid) {
		set("vmcustomerid", vmcustomerid);
	}

	public java.lang.Long getVmcustomerid() {
		return get("vmcustomerid");
	}

	public void setName(java.lang.String name) {
		set("name", name);
	}

	public java.lang.String getName() {
		return get("name");
	}

	public void setPictureurlid(java.lang.String pictureurlid) {
		set("pictureurlid", pictureurlid);
	}

	public java.lang.String getPictureurlid() {
		return get("pictureurlid");
	}

	public void setBuyprice(java.math.BigDecimal buyprice) {
		set("buyprice", buyprice);
	}

	public java.math.BigDecimal getBuyprice() {
		return get("buyprice");
	}

	public void setUpdatetime(java.util.Date updatetime) {
		set("updatetime", updatetime);
	}

	public java.util.Date getUpdatetime() {
		return get("updatetime");
	}

	public void setUpdaterealname(java.lang.String updaterealname) {
		set("updaterealname", updaterealname);
	}

	public java.lang.String getUpdaterealname() {
		return get("updaterealname");
	}

}
