package com.jfinal.weixin.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseAppUserppn<M extends BaseAppUserppn<M>> extends Model<M> implements IBean {

	public void setUserid(java.lang.Long userid) {
		set("userid", userid);
	}

	public java.lang.Long getUserid() {
		return get("userid");
	}

	public void setPpnid(java.lang.Long ppnid) {
		set("ppnid", ppnid);
	}

	public java.lang.Long getPpnid() {
		return get("ppnid");
	}

	public void setInserttime(java.util.Date inserttime) {
		set("inserttime", inserttime);
	}

	public java.util.Date getInserttime() {
		return get("inserttime");
	}

	public void setReadflag(java.lang.Integer readflag) {
		set("readflag", readflag);
	}

	public java.lang.Integer getReadflag() {
		return get("readflag");
	}

	public void setFirstreadtime(java.util.Date firstreadtime) {
		set("firstreadtime", firstreadtime);
	}

	public java.util.Date getFirstreadtime() {
		return get("firstreadtime");
	}

	public void setFirstreadpoint(java.lang.Integer firstreadpoint) {
		set("firstreadpoint", firstreadpoint);
	}

	public java.lang.Integer getFirstreadpoint() {
		return get("firstreadpoint");
	}

	public void setTotalreadcount(java.lang.Long totalreadcount) {
		set("totalreadcount", totalreadcount);
	}

	public java.lang.Long getTotalreadcount() {
		return get("totalreadcount");
	}

	public void setLastreadtime(java.util.Date lastreadtime) {
		set("lastreadtime", lastreadtime);
	}

	public java.util.Date getLastreadtime() {
		return get("lastreadtime");
	}

}
