package com.jfinal.weixin.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseAndroidnetinfo<M extends BaseAndroidnetinfo<M>> extends Model<M> implements IBean {

	public void setDeviceid(java.lang.String deviceid) {
		set("deviceid", deviceid);
	}

	public java.lang.String getDeviceid() {
		return get("deviceid");
	}

	public void setLastnettime(java.util.Date lastnettime) {
		set("lastnettime", lastnettime);
	}

	public java.util.Date getLastnettime() {
		return get("lastnettime");
	}

	public void setLastnettype(java.lang.String lastnettype) {
		set("lastnettype", lastnettype);
	}

	public java.lang.String getLastnettype() {
		return get("lastnettype");
	}

	public void setIpaddress(java.lang.String ipaddress) {
		set("ipaddress", ipaddress);
	}

	public java.lang.String getIpaddress() {
		return get("ipaddress");
	}

	public void setLongitude(java.lang.Double longitude) {
		set("longitude", longitude);
	}

	public java.lang.Double getLongitude() {
		return get("longitude");
	}

	public void setLatitude(java.lang.Double latitude) {
		set("latitude", latitude);
	}

	public java.lang.Double getLatitude() {
		return get("latitude");
	}

}
