package com.jfinal.weixin.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseViewAndroidnetappstartLogLast<M extends BaseViewAndroidnetappstartLogLast<M>> extends Model<M> implements IBean {

	public void setDeviceid(java.lang.String deviceid) {
		set("deviceid", deviceid);
	}

	public java.lang.String getDeviceid() {
		return get("deviceid");
	}

	public void setAppstarttime(java.util.Date appstarttime) {
		set("appstarttime", appstarttime);
	}

	public java.util.Date getAppstarttime() {
		return get("appstarttime");
	}

}
