package com.jfinal.weixin.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseAndroidnetappstartLog<M extends BaseAndroidnetappstartLog<M>> extends Model<M> implements IBean {

	public void setDeviceid(java.lang.String deviceid) {
		set("deviceid", deviceid);
	}

	public java.lang.String getDeviceid() {
		return get("deviceid");
	}

	public void setStarttype(java.lang.String starttype) {
		set("starttype", starttype);
	}

	public java.lang.String getStarttype() {
		return get("starttype");
	}

	public void setAppstarttime(java.util.Date appstarttime) {
		set("appstarttime", appstarttime);
	}

	public java.util.Date getAppstarttime() {
		return get("appstarttime");
	}

	public void setIpaddress(java.lang.String ipaddress) {
		set("ipaddress", ipaddress);
	}

	public java.lang.String getIpaddress() {
		return get("ipaddress");
	}

	public void setPkgname(java.lang.String pkgname) {
		set("pkgname", pkgname);
	}

	public java.lang.String getPkgname() {
		return get("pkgname");
	}

	public void setApkversion(java.lang.Integer apkversion) {
		set("apkversion", apkversion);
	}

	public java.lang.Integer getApkversion() {
		return get("apkversion");
	}

}
