package com.jfinal.weixin.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseAndroidsalelist<M extends BaseAndroidsalelist<M>> extends Model<M> implements IBean {

	public void setDeviceid(java.lang.String deviceid) {
		set("deviceid", deviceid);
	}

	public java.lang.String getDeviceid() {
		return get("deviceid");
	}

	public void setServertime(java.util.Date servertime) {
		set("servertime", servertime);
	}

	public java.util.Date getServertime() {
		return get("servertime");
	}

	public void setSaletime(java.util.Date saletime) {
		set("saletime", saletime);
	}

	public java.util.Date getSaletime() {
		return get("saletime");
	}

	public void setOuttype(java.lang.String outtype) {
		set("outtype", outtype);
	}

	public java.lang.String getOuttype() {
		return get("outtype");
	}

	public void setTrackno(java.lang.String trackno) {
		set("trackno", trackno);
	}

	public java.lang.String getTrackno() {
		return get("trackno");
	}

	public void setMingcheng(java.lang.String mingcheng) {
		set("mingcheng", mingcheng);
	}

	public java.lang.String getMingcheng() {
		return get("mingcheng");
	}

	public void setBuyprice(java.math.BigDecimal buyprice) {
		set("buyprice", buyprice);
	}

	public java.math.BigDecimal getBuyprice() {
		return get("buyprice");
	}

	public void setPrice(java.math.BigDecimal price) {
		set("price", price);
	}

	public java.math.BigDecimal getPrice() {
		return get("price");
	}

	public void setPayway(java.lang.String payway) {
		set("payway", payway);
	}

	public java.lang.String getPayway() {
		return get("payway");
	}

	public void setOpenid(java.lang.String openid) {
		set("openid", openid);
	}

	public java.lang.String getOpenid() {
		return get("openid");
	}

	public void setTranid(java.lang.String tranid) {
		set("tranid", tranid);
	}

	public java.lang.String getTranid() {
		return get("tranid");
	}

	public void setYyyymm(java.lang.String yyyymm) {
		set("yyyymm", yyyymm);
	}

	public java.lang.String getYyyymm() {
		return get("yyyymm");
	}

	public void setYyyymmdd(java.lang.String yyyymmdd) {
		set("yyyymmdd", yyyymmdd);
	}

	public java.lang.String getYyyymmdd() {
		return get("yyyymmdd");
	}

}
