package com.jfinal.weixin.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseAppOperater<M extends BaseAppOperater<M>> extends Model<M> implements IBean {

	public void setId(java.math.BigInteger id) {
		set("id", id);
	}

	public java.math.BigInteger getId() {
		return get("id");
	}

	public void setUserId(java.lang.String userId) {
		set("user_id", userId);
	}

	public java.lang.String getUserId() {
		return get("user_id");
	}

	public void setPassword(java.lang.String password) {
		set("password", password);
	}

	public java.lang.String getPassword() {
		return get("password");
	}

	public void setUserName(java.lang.String userName) {
		set("user_name", userName);
	}

	public java.lang.String getUserName() {
		return get("user_name");
	}

	public void setPwderrorcount(java.lang.Integer pwderrorcount) {
		set("pwderrorcount", pwderrorcount);
	}

	public java.lang.Integer getPwderrorcount() {
		return get("pwderrorcount");
	}

	public void setFlgDeleted(java.lang.Integer flgDeleted) {
		set("flg_deleted", flgDeleted);
	}

	public java.lang.Integer getFlgDeleted() {
		return get("flg_deleted");
	}

	public void setLoginip(java.lang.String loginip) {
		set("loginip", loginip);
	}

	public java.lang.String getLoginip() {
		return get("loginip");
	}

	public void setLogintime(java.util.Date logintime) {
		set("logintime", logintime);
	}

	public java.util.Date getLogintime() {
		return get("logintime");
	}

	public void setIdCrtUser(java.math.BigInteger idCrtUser) {
		set("id_crt_user", idCrtUser);
	}

	public java.math.BigInteger getIdCrtUser() {
		return get("id_crt_user");
	}

	public void setTimeCrt(java.util.Date timeCrt) {
		set("time_crt", timeCrt);
	}

	public java.util.Date getTimeCrt() {
		return get("time_crt");
	}

	public void setIdUpdUser(java.math.BigInteger idUpdUser) {
		set("id_upd_user", idUpdUser);
	}

	public java.math.BigInteger getIdUpdUser() {
		return get("id_upd_user");
	}

	public void setTimeUpd(java.util.Date timeUpd) {
		set("time_upd", timeUpd);
	}

	public java.util.Date getTimeUpd() {
		return get("time_upd");
	}

}
