package com.jfinal.weixin.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseLatestappversion<M extends BaseLatestappversion<M>> extends Model<M> implements IBean {

	public void setApkname(java.lang.String apkname) {
		set("apkname", apkname);
	}

	public java.lang.String getApkname() {
		return get("apkname");
	}

	public void setApkversion(java.lang.Integer apkversion) {
		set("apkversion", apkversion);
	}

	public java.lang.Integer getApkversion() {
		return get("apkversion");
	}

	public void setDownloadurl(java.lang.String downloadurl) {
		set("downloadurl", downloadurl);
	}

	public java.lang.String getDownloadurl() {
		return get("downloadurl");
	}

	public void setUpdatetime(java.util.Date updatetime) {
		set("updatetime", updatetime);
	}

	public java.util.Date getUpdatetime() {
		return get("updatetime");
	}

	public void setApkinstruction(java.lang.String apkinstruction) {
		set("apkinstruction", apkinstruction);
	}

	public java.lang.String getApkinstruction() {
		return get("apkinstruction");
	}

}
