package com.jfinal.weixin.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseWxidChargeCardno<M extends BaseWxidChargeCardno<M>> extends Model<M> implements IBean {

	public void setChargeid(java.math.BigInteger chargeid) {
		set("chargeid", chargeid);
	}

	public java.math.BigInteger getChargeid() {
		return get("chargeid");
	}

	public void setTransid(java.lang.String transid) {
		set("transid", transid);
	}

	public java.lang.String getTransid() {
		return get("transid");
	}

	public void setOutTradeNo(java.lang.String outTradeNo) {
		set("out_trade_no", outTradeNo);
	}

	public java.lang.String getOutTradeNo() {
		return get("out_trade_no");
	}

	public void setFanopenid(java.lang.String fanopenid) {
		set("fanopenid", fanopenid);
	}

	public java.lang.String getFanopenid() {
		return get("fanopenid");
	}

	public void setWxopenid(java.lang.String wxopenid) {
		set("wxopenid", wxopenid);
	}

	public java.lang.String getWxopenid() {
		return get("wxopenid");
	}

	public void setIdcardno(java.lang.String idcardno) {
		set("idcardno", idcardno);
	}

	public java.lang.String getIdcardno() {
		return get("idcardno");
	}

	public void setMoneyfen(java.lang.Integer moneyfen) {
		set("moneyfen", moneyfen);
	}

	public java.lang.Integer getMoneyfen() {
		return get("moneyfen");
	}

	public void setInserttime(java.util.Date inserttime) {
		set("inserttime", inserttime);
	}

	public java.util.Date getInserttime() {
		return get("inserttime");
	}

}
