package com.jfinal.weixin.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseVmmisuserpara<M extends BaseVmmisuserpara<M>> extends Model<M> implements IBean {

	public void setUserid(java.lang.Long userid) {
		set("userid", userid);
	}

	public java.lang.Long getUserid() {
		return get("userid");
	}

	public void setPagerecords(java.lang.Integer pagerecords) {
		set("pagerecords", pagerecords);
	}

	public java.lang.Integer getPagerecords() {
		return get("pagerecords");
	}

	public void setUpdatetime(java.util.Date updatetime) {
		set("updatetime", updatetime);
	}

	public java.util.Date getUpdatetime() {
		return get("updatetime");
	}

	public void setVmmisuserparaid(java.lang.Long vmmisuserparaid) {
		set("vmmisuserparaid", vmmisuserparaid);
	}

	public java.lang.Long getVmmisuserparaid() {
		return get("vmmisuserparaid");
	}

}
