package com.jfinal.weixin.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseVmmisuserLog<M extends BaseVmmisuserLog<M>> extends Model<M> implements IBean {

	public void setLogid(java.math.BigInteger logid) {
		set("logid", logid);
	}

	public java.math.BigInteger getLogid() {
		return get("logid");
	}

	public void setIpaddress(java.lang.String ipaddress) {
		set("ipaddress", ipaddress);
	}

	public java.lang.String getIpaddress() {
		return get("ipaddress");
	}

	public void setLogintime(java.util.Date logintime) {
		set("logintime", logintime);
	}

	public java.util.Date getLogintime() {
		return get("logintime");
	}

	public void setLoginname(java.lang.String loginname) {
		set("loginname", loginname);
	}

	public java.lang.String getLoginname() {
		return get("loginname");
	}

	public void setPassword(java.lang.String password) {
		set("password", password);
	}

	public java.lang.String getPassword() {
		return get("password");
	}

	public void setCode(java.lang.String code) {
		set("code", code);
	}

	public java.lang.String getCode() {
		return get("code");
	}

	public void setIresult(java.lang.Integer iresult) {
		set("iresult", iresult);
	}

	public java.lang.Integer getIresult() {
		return get("iresult");
	}

}
