package com.jfinal.weixin.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseAppUserpointexrecord<M extends BaseAppUserpointexrecord<M>> extends Model<M> implements IBean {

	public void setPointexrecordid(java.math.BigInteger pointexrecordid) {
		set("pointexrecordid", pointexrecordid);
	}

	public java.math.BigInteger getPointexrecordid() {
		return get("pointexrecordid");
	}

	public void setUserid(java.lang.Long userid) {
		set("userid", userid);
	}

	public java.lang.Long getUserid() {
		return get("userid");
	}

	public void setPointexid(java.lang.Long pointexid) {
		set("pointexid", pointexid);
	}

	public java.lang.Long getPointexid() {
		return get("pointexid");
	}

	public void setExdate(java.util.Date exdate) {
		set("exdate", exdate);
	}

	public java.util.Date getExdate() {
		return get("exdate");
	}

	public void setExtime(java.util.Date extime) {
		set("extime", extime);
	}

	public java.util.Date getExtime() {
		return get("extime");
	}

	public void setExcount(java.lang.Integer excount) {
		set("excount", excount);
	}

	public java.lang.Integer getExcount() {
		return get("excount");
	}

	public void setExstatus(java.lang.String exstatus) {
		set("exstatus", exstatus);
	}

	public java.lang.String getExstatus() {
		return get("exstatus");
	}

	public void setMailname(java.lang.String mailname) {
		set("mailname", mailname);
	}

	public java.lang.String getMailname() {
		return get("mailname");
	}

	public void setMailmobile(java.lang.String mailmobile) {
		set("mailmobile", mailmobile);
	}

	public java.lang.String getMailmobile() {
		return get("mailmobile");
	}

	public void setMailaddress(java.lang.String mailaddress) {
		set("mailaddress", mailaddress);
	}

	public java.lang.String getMailaddress() {
		return get("mailaddress");
	}

	public void setMailno(java.lang.String mailno) {
		set("mailno", mailno);
	}

	public java.lang.String getMailno() {
		return get("mailno");
	}

	public void setSendmaildate(java.util.Date sendmaildate) {
		set("sendmaildate", sendmaildate);
	}

	public java.util.Date getSendmaildate() {
		return get("sendmaildate");
	}

}
