package com.jfinal.weixin.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BasePayokHistory<M extends BasePayokHistory<M>> extends Model<M> implements IBean {

	public void setPayway(java.lang.String payway) {
		set("payway", payway);
	}

	public java.lang.String getPayway() {
		return get("payway");
	}

	public void setOwner(java.lang.String owner) {
		set("owner", owner);
	}

	public java.lang.String getOwner() {
		return get("owner");
	}

	public void setTranid(java.lang.String tranid) {
		set("tranid", tranid);
	}

	public java.lang.String getTranid() {
		return get("tranid");
	}

	public void setOuttradeno(java.lang.String outtradeno) {
		set("outtradeno", outtradeno);
	}

	public java.lang.String getOuttradeno() {
		return get("outtradeno");
	}

	public void setOpenid(java.lang.String openid) {
		set("openid", openid);
	}

	public java.lang.String getOpenid() {
		return get("openid");
	}

	public void setDeviceid(java.lang.String deviceid) {
		set("deviceid", deviceid);
	}

	public java.lang.String getDeviceid() {
		return get("deviceid");
	}

	public void setTrackno(java.lang.String trackno) {
		set("trackno", trackno);
	}

	public java.lang.String getTrackno() {
		return get("trackno");
	}

	public void setPrice(java.lang.String price) {
		set("price", price);
	}

	public java.lang.String getPrice() {
		return get("price");
	}

	public void setYyyymmdd(java.lang.String yyyymmdd) {
		set("yyyymmdd", yyyymmdd);
	}

	public java.lang.String getYyyymmdd() {
		return get("yyyymmdd");
	}

	public void setInserttime(java.util.Date inserttime) {
		set("inserttime", inserttime);
	}

	public java.util.Date getInserttime() {
		return get("inserttime");
	}

	public void setRealname(java.lang.String realname) {
		set("realname", realname);
	}

	public java.lang.String getRealname() {
		return get("realname");
	}

}
