package com.jfinal.weixin.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseAppUserinfo<M extends BaseAppUserinfo<M>> extends Model<M> implements IBean {

	public void setUserid(java.math.BigInteger userid) {
		set("userid", userid);
	}

	public java.math.BigInteger getUserid() {
		return get("userid");
	}

	public void setMobileno(java.lang.String mobileno) {
		set("mobileno", mobileno);
	}

	public java.lang.String getMobileno() {
		return get("mobileno");
	}

	public void setPassword(java.lang.String password) {
		set("password", password);
	}

	public java.lang.String getPassword() {
		return get("password");
	}

	public void setMoney(java.math.BigDecimal money) {
		set("money", money);
	}

	public java.math.BigDecimal getMoney() {
		return get("money");
	}

	public void setPoint(java.lang.Long point) {
		set("point", point);
	}

	public java.lang.Long getPoint() {
		return get("point");
	}

	public void setMobileid1(java.lang.String mobileid1) {
		set("mobileid1", mobileid1);
	}

	public java.lang.String getMobileid1() {
		return get("mobileid1");
	}

	public void setMobileid2(java.lang.String mobileid2) {
		set("mobileid2", mobileid2);
	}

	public java.lang.String getMobileid2() {
		return get("mobileid2");
	}

	public void setMobileid3(java.lang.String mobileid3) {
		set("mobileid3", mobileid3);
	}

	public java.lang.String getMobileid3() {
		return get("mobileid3");
	}

	public void setMobiletype(java.lang.String mobiletype) {
		set("mobiletype", mobiletype);
	}

	public java.lang.String getMobiletype() {
		return get("mobiletype");
	}

	public void setMobilebrand(java.lang.String mobilebrand) {
		set("mobilebrand", mobilebrand);
	}

	public java.lang.String getMobilebrand() {
		return get("mobilebrand");
	}

	public void setMobileosversion(java.lang.String mobileosversion) {
		set("mobileosversion", mobileosversion);
	}

	public java.lang.String getMobileosversion() {
		return get("mobileosversion");
	}

	public void setSessionid(java.lang.String sessionid) {
		set("sessionid", sessionid);
	}

	public java.lang.String getSessionid() {
		return get("sessionid");
	}

	public void setRegistetime(java.util.Date registetime) {
		set("registetime", registetime);
	}

	public java.util.Date getRegistetime() {
		return get("registetime");
	}

	public void setNickname(java.lang.String nickname) {
		set("nickname", nickname);
	}

	public java.lang.String getNickname() {
		return get("nickname");
	}

	public void setHeadurl(java.lang.String headurl) {
		set("headurl", headurl);
	}

	public java.lang.String getHeadurl() {
		return get("headurl");
	}

	public void setReceivername(java.lang.String receivername) {
		set("receivername", receivername);
	}

	public java.lang.String getReceivername() {
		return get("receivername");
	}

	public void setReceiveraddress(java.lang.String receiveraddress) {
		set("receiveraddress", receiveraddress);
	}

	public java.lang.String getReceiveraddress() {
		return get("receiveraddress");
	}

	public void setLoginip(java.lang.String loginip) {
		set("loginip", loginip);
	}

	public java.lang.String getLoginip() {
		return get("loginip");
	}

	public void setLogintime(java.util.Date logintime) {
		set("logintime", logintime);
	}

	public java.util.Date getLogintime() {
		return get("logintime");
	}

	public void setAppversion(java.lang.Integer appversion) {
		set("appversion", appversion);
	}

	public java.lang.Integer getAppversion() {
		return get("appversion");
	}

	public void setReceivemobile(java.lang.String receivemobile) {
		set("receivemobile", receivemobile);
	}

	public java.lang.String getReceivemobile() {
		return get("receivemobile");
	}

}
