package com.jfinal.weixin.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseWxFaninfo<M extends BaseWxFaninfo<M>> extends Model<M> implements IBean {

	public void setOwneropenid(java.lang.String owneropenid) {
		set("owneropenid", owneropenid);
	}

	public java.lang.String getOwneropenid() {
		return get("owneropenid");
	}

	public void setFanopenid(java.lang.String fanopenid) {
		set("fanopenid", fanopenid);
	}

	public java.lang.String getFanopenid() {
		return get("fanopenid");
	}

	public void setEventkey(java.lang.String eventkey) {
		set("eventkey", eventkey);
	}

	public java.lang.String getEventkey() {
		return get("eventkey");
	}

	public void setAddtime(java.util.Date addtime) {
		set("addtime", addtime);
	}

	public java.util.Date getAddtime() {
		return get("addtime");
	}

	public void setGetgoodcode(java.lang.String getgoodcode) {
		set("getgoodcode", getgoodcode);
	}

	public java.lang.String getGetgoodcode() {
		return get("getgoodcode");
	}

	public void setGetgoodtime(java.util.Date getgoodtime) {
		set("getgoodtime", getgoodtime);
	}

	public java.util.Date getGetgoodtime() {
		return get("getgoodtime");
	}

	public void setGettrackno(java.lang.String gettrackno) {
		set("gettrackno", gettrackno);
	}

	public java.lang.String getGettrackno() {
		return get("gettrackno");
	}

	public void setGetgoodname(java.lang.String getgoodname) {
		set("getgoodname", getgoodname);
	}

	public java.lang.String getGetgoodname() {
		return get("getgoodname");
	}

	public void setGetandroidid(java.lang.String getandroidid) {
		set("getandroidid", getandroidid);
	}

	public java.lang.String getGetandroidid() {
		return get("getandroidid");
	}

}
