package com.jfinal.weixin.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseIdVmrechargecard<M extends BaseIdVmrechargecard<M>> extends Model<M> implements IBean {

	public void setRechargecardid(java.lang.Long rechargecardid) {
		set("rechargecardid", rechargecardid);
	}

	public java.lang.Long getRechargecardid() {
		return get("rechargecardid");
	}

	public void setAddtime(java.util.Date addtime) {
		set("addtime", addtime);
	}

	public java.util.Date getAddtime() {
		return get("addtime");
	}

	public void setCardsid(java.lang.Long cardsid) {
		set("cardsid", cardsid);
	}

	public java.lang.Long getCardsid() {
		return get("cardsid");
	}

	public void setDescription(java.lang.String description) {
		set("description", description);
	}

	public java.lang.String getDescription() {
		return get("description");
	}

	public void setExpensebalance(java.lang.Double expensebalance) {
		set("expensebalance", expensebalance);
	}

	public java.lang.Double getExpensebalance() {
		return get("expensebalance");
	}

	public void setRecharge(java.lang.Double recharge) {
		set("recharge", recharge);
	}

	public java.lang.Double getRecharge() {
		return get("recharge");
	}

	public void setUpdaterealname(java.lang.String updaterealname) {
		set("updaterealname", updaterealname);
	}

	public java.lang.String getUpdaterealname() {
		return get("updaterealname");
	}

	public void setHistory(java.lang.Double history) {
		set("history", history);
	}

	public java.lang.Double getHistory() {
		return get("history");
	}

}
