package com.jfinal.weixin.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseAppGoodsurl<M extends BaseAppGoodsurl<M>> extends Model<M> implements IBean {

	public void setGoodurlid(java.lang.Long goodurlid) {
		set("goodurlid", goodurlid);
	}

	public java.lang.Long getGoodurlid() {
		return get("goodurlid");
	}

	public void setName(java.lang.String name) {
		set("name", name);
	}

	public java.lang.String getName() {
		return get("name");
	}

	public void setPicturename(java.lang.String picturename) {
		set("picturename", picturename);
	}

	public java.lang.String getPicturename() {
		return get("picturename");
	}

	public void setDeleteflag(java.lang.String deleteflag) {
		set("deleteflag", deleteflag);
	}

	public java.lang.String getDeleteflag() {
		return get("deleteflag");
	}

	public void setPictureurl(java.lang.String pictureurl) {
		set("pictureurl", pictureurl);
	}

	public java.lang.String getPictureurl() {
		return get("pictureurl");
	}

	public void setType(java.lang.String type) {
		set("type", type);
	}

	public java.lang.String getType() {
		return get("type");
	}

}
