package com.jfinal.weixin.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseHzcityblack<M extends BaseHzcityblack<M>> extends Model<M> implements IBean {

	public void setBlackid(java.lang.Integer blackid) {
		set("blackid", blackid);
	}

	public java.lang.Integer getBlackid() {
		return get("blackid");
	}

	public void setBlackcardno(java.lang.String blackcardno) {
		set("blackcardno", blackcardno);
	}

	public java.lang.String getBlackcardno() {
		return get("blackcardno");
	}

}
