package com.jfinal.weixin.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseChenmonth<M extends BaseChenmonth<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public void setC01(java.lang.Integer c01) {
		set("c01", c01);
	}

	public java.lang.Integer getC01() {
		return get("c01");
	}

	public void setN01(java.lang.Integer n01) {
		set("n01", n01);
	}

	public java.lang.Integer getN01() {
		return get("n01");
	}

	public void setC02(java.lang.Integer c02) {
		set("c02", c02);
	}

	public java.lang.Integer getC02() {
		return get("c02");
	}

	public void setN02(java.lang.Integer n02) {
		set("n02", n02);
	}

	public java.lang.Integer getN02() {
		return get("n02");
	}

	public void setC03(java.lang.Integer c03) {
		set("c03", c03);
	}

	public java.lang.Integer getC03() {
		return get("c03");
	}

	public void setN03(java.lang.Integer n03) {
		set("n03", n03);
	}

	public java.lang.Integer getN03() {
		return get("n03");
	}

	public void setC04(java.lang.Integer c04) {
		set("c04", c04);
	}

	public java.lang.Integer getC04() {
		return get("c04");
	}

	public void setN04(java.lang.Integer n04) {
		set("n04", n04);
	}

	public java.lang.Integer getN04() {
		return get("n04");
	}

	public void setC05(java.lang.Integer c05) {
		set("c05", c05);
	}

	public java.lang.Integer getC05() {
		return get("c05");
	}

	public void setN05(java.lang.Integer n05) {
		set("n05", n05);
	}

	public java.lang.Integer getN05() {
		return get("n05");
	}

	public void setC06(java.lang.Integer c06) {
		set("c06", c06);
	}

	public java.lang.Integer getC06() {
		return get("c06");
	}

	public void setN06(java.lang.Integer n06) {
		set("n06", n06);
	}

	public java.lang.Integer getN06() {
		return get("n06");
	}

	public void setC07(java.lang.Integer c07) {
		set("c07", c07);
	}

	public java.lang.Integer getC07() {
		return get("c07");
	}

	public void setN07(java.lang.Integer n07) {
		set("n07", n07);
	}

	public java.lang.Integer getN07() {
		return get("n07");
	}

	public void setC08(java.lang.Integer c08) {
		set("c08", c08);
	}

	public java.lang.Integer getC08() {
		return get("c08");
	}

	public void setN08(java.lang.Integer n08) {
		set("n08", n08);
	}

	public java.lang.Integer getN08() {
		return get("n08");
	}

	public void setC09(java.lang.Integer c09) {
		set("c09", c09);
	}

	public java.lang.Integer getC09() {
		return get("c09");
	}

	public void setN09(java.lang.Integer n09) {
		set("n09", n09);
	}

	public java.lang.Integer getN09() {
		return get("n09");
	}

	public void setC10(java.lang.Integer c10) {
		set("c10", c10);
	}

	public java.lang.Integer getC10() {
		return get("c10");
	}

	public void setN10(java.lang.Integer n10) {
		set("n10", n10);
	}

	public java.lang.Integer getN10() {
		return get("n10");
	}

	public void setC11(java.lang.Integer c11) {
		set("c11", c11);
	}

	public java.lang.Integer getC11() {
		return get("c11");
	}

	public void setN11(java.lang.Integer n11) {
		set("n11", n11);
	}

	public java.lang.Integer getN11() {
		return get("n11");
	}

	public void setC12(java.lang.Integer c12) {
		set("c12", c12);
	}

	public java.lang.Integer getC12() {
		return get("c12");
	}

	public void setN12(java.lang.Integer n12) {
		set("n12", n12);
	}

	public java.lang.Integer getN12() {
		return get("n12");
	}

	public void setC13(java.lang.Integer c13) {
		set("c13", c13);
	}

	public java.lang.Integer getC13() {
		return get("c13");
	}

	public void setN13(java.lang.Integer n13) {
		set("n13", n13);
	}

	public java.lang.Integer getN13() {
		return get("n13");
	}

	public void setC14(java.lang.Integer c14) {
		set("c14", c14);
	}

	public java.lang.Integer getC14() {
		return get("c14");
	}

	public void setN14(java.lang.Integer n14) {
		set("n14", n14);
	}

	public java.lang.Integer getN14() {
		return get("n14");
	}

	public void setC15(java.lang.Integer c15) {
		set("c15", c15);
	}

	public java.lang.Integer getC15() {
		return get("c15");
	}

	public void setN15(java.lang.Integer n15) {
		set("n15", n15);
	}

	public java.lang.Integer getN15() {
		return get("n15");
	}

	public void setC16(java.lang.Integer c16) {
		set("c16", c16);
	}

	public java.lang.Integer getC16() {
		return get("c16");
	}

	public void setN16(java.lang.Integer n16) {
		set("n16", n16);
	}

	public java.lang.Integer getN16() {
		return get("n16");
	}

	public void setC17(java.lang.Integer c17) {
		set("c17", c17);
	}

	public java.lang.Integer getC17() {
		return get("c17");
	}

	public void setN17(java.lang.Integer n17) {
		set("n17", n17);
	}

	public java.lang.Integer getN17() {
		return get("n17");
	}

	public void setC18(java.lang.Integer c18) {
		set("c18", c18);
	}

	public java.lang.Integer getC18() {
		return get("c18");
	}

	public void setN18(java.lang.Integer n18) {
		set("n18", n18);
	}

	public java.lang.Integer getN18() {
		return get("n18");
	}

	public void setC19(java.lang.Integer c19) {
		set("c19", c19);
	}

	public java.lang.Integer getC19() {
		return get("c19");
	}

	public void setN19(java.lang.Integer n19) {
		set("n19", n19);
	}

	public java.lang.Integer getN19() {
		return get("n19");
	}

	public void setC20(java.lang.Integer c20) {
		set("c20", c20);
	}

	public java.lang.Integer getC20() {
		return get("c20");
	}

	public void setN20(java.lang.Integer n20) {
		set("n20", n20);
	}

	public java.lang.Integer getN20() {
		return get("n20");
	}

	public void setC21(java.lang.Integer c21) {
		set("c21", c21);
	}

	public java.lang.Integer getC21() {
		return get("c21");
	}

	public void setN21(java.lang.Integer n21) {
		set("n21", n21);
	}

	public java.lang.Integer getN21() {
		return get("n21");
	}

	public void setC22(java.lang.Integer c22) {
		set("c22", c22);
	}

	public java.lang.Integer getC22() {
		return get("c22");
	}

	public void setN22(java.lang.Integer n22) {
		set("n22", n22);
	}

	public java.lang.Integer getN22() {
		return get("n22");
	}

	public void setC23(java.lang.Integer c23) {
		set("c23", c23);
	}

	public java.lang.Integer getC23() {
		return get("c23");
	}

	public void setN23(java.lang.Integer n23) {
		set("n23", n23);
	}

	public java.lang.Integer getN23() {
		return get("n23");
	}

	public void setC24(java.lang.Integer c24) {
		set("c24", c24);
	}

	public java.lang.Integer getC24() {
		return get("c24");
	}

	public void setN24(java.lang.Integer n24) {
		set("n24", n24);
	}

	public java.lang.Integer getN24() {
		return get("n24");
	}

	public void setC25(java.lang.Integer c25) {
		set("c25", c25);
	}

	public java.lang.Integer getC25() {
		return get("c25");
	}

	public void setN25(java.lang.Integer n25) {
		set("n25", n25);
	}

	public java.lang.Integer getN25() {
		return get("n25");
	}

	public void setC26(java.lang.Integer c26) {
		set("c26", c26);
	}

	public java.lang.Integer getC26() {
		return get("c26");
	}

	public void setN26(java.lang.Integer n26) {
		set("n26", n26);
	}

	public java.lang.Integer getN26() {
		return get("n26");
	}

	public void setC27(java.lang.Integer c27) {
		set("c27", c27);
	}

	public java.lang.Integer getC27() {
		return get("c27");
	}

	public void setN27(java.lang.Integer n27) {
		set("n27", n27);
	}

	public java.lang.Integer getN27() {
		return get("n27");
	}

	public void setC28(java.lang.Integer c28) {
		set("c28", c28);
	}

	public java.lang.Integer getC28() {
		return get("c28");
	}

	public void setN28(java.lang.Integer n28) {
		set("n28", n28);
	}

	public java.lang.Integer getN28() {
		return get("n28");
	}

	public void setC29(java.lang.Integer c29) {
		set("c29", c29);
	}

	public java.lang.Integer getC29() {
		return get("c29");
	}

	public void setN29(java.lang.Integer n29) {
		set("n29", n29);
	}

	public java.lang.Integer getN29() {
		return get("n29");
	}

	public void setC30(java.lang.Integer c30) {
		set("c30", c30);
	}

	public java.lang.Integer getC30() {
		return get("c30");
	}

	public void setN30(java.lang.Integer n30) {
		set("n30", n30);
	}

	public java.lang.Integer getN30() {
		return get("n30");
	}

	public void setC31(java.lang.Integer c31) {
		set("c31", c31);
	}

	public java.lang.Integer getC31() {
		return get("c31");
	}

	public void setN31(java.lang.Integer n31) {
		set("n31", n31);
	}

	public java.lang.Integer getN31() {
		return get("n31");
	}

}
