package com.jfinal.weixin.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseIdVmunit<M extends BaseIdVmunit<M>> extends Model<M> implements IBean {

	public void setUnitid(java.lang.Long unitid) {
		set("unitid", unitid);
	}

	public java.lang.Long getUnitid() {
		return get("unitid");
	}

	public void setAddrealname(java.lang.String addrealname) {
		set("addrealname", addrealname);
	}

	public java.lang.String getAddrealname() {
		return get("addrealname");
	}

	public void setAddtime(java.util.Date addtime) {
		set("addtime", addtime);
	}

	public java.util.Date getAddtime() {
		return get("addtime");
	}

	public void setSunitname(java.lang.String sunitname) {
		set("sunitname", sunitname);
	}

	public java.lang.String getSunitname() {
		return get("sunitname");
	}

	public void setUnitadderss(java.lang.String unitadderss) {
		set("unitadderss", unitadderss);
	}

	public java.lang.String getUnitadderss() {
		return get("unitadderss");
	}

	public void setUnitbalance(java.lang.Double unitbalance) {
		set("unitbalance", unitbalance);
	}

	public java.lang.Double getUnitbalance() {
		return get("unitbalance");
	}

	public void setUnitname(java.lang.String unitname) {
		set("unitname", unitname);
	}

	public java.lang.String getUnitname() {
		return get("unitname");
	}

	public void setUnitphone(java.lang.String unitphone) {
		set("unitphone", unitphone);
	}

	public java.lang.String getUnitphone() {
		return get("unitphone");
	}

	public void setUnitprincipal(java.lang.String unitprincipal) {
		set("unitprincipal", unitprincipal);
	}

	public java.lang.String getUnitprincipal() {
		return get("unitprincipal");
	}

	public void setVmcustomerid(java.lang.Long vmcustomerid) {
		set("vmcustomerid", vmcustomerid);
	}

	public java.lang.Long getVmcustomerid() {
		return get("vmcustomerid");
	}

}
