package com.jfinal.weixin.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseIdVmexpenserecord<M extends BaseIdVmexpenserecord<M>> extends Model<M> implements IBean {

	public void setExpenserecordid(java.lang.Long expenserecordid) {
		set("expenserecordid", expenserecordid);
	}

	public java.lang.Long getExpenserecordid() {
		return get("expenserecordid");
	}

	public void setAddtime(java.util.Date addtime) {
		set("addtime", addtime);
	}

	public java.util.Date getAddtime() {
		return get("addtime");
	}

	public void setCardsid(java.lang.Long cardsid) {
		set("cardsid", cardsid);
	}

	public java.lang.Long getCardsid() {
		return get("cardsid");
	}

	public void setDescription(java.lang.String description) {
		set("description", description);
	}

	public java.lang.String getDescription() {
		return get("description");
	}

	public void setExpense(java.lang.Double expense) {
		set("expense", expense);
	}

	public java.lang.Double getExpense() {
		return get("expense");
	}

	public void setExpensebalance(java.lang.Double expensebalance) {
		set("expensebalance", expensebalance);
	}

	public java.lang.Double getExpensebalance() {
		return get("expensebalance");
	}

	public void setMachine(java.lang.String machine) {
		set("machine", machine);
	}

	public java.lang.String getMachine() {
		return get("machine");
	}

	public void setProducts(java.lang.String products) {
		set("products", products);
	}

	public java.lang.String getProducts() {
		return get("products");
	}

	public void setTransactionflow(java.lang.String transactionflow) {
		set("transactionflow", transactionflow);
	}

	public java.lang.String getTransactionflow() {
		return get("transactionflow");
	}

	public void setType(java.lang.Integer type) {
		set("type", type);
	}

	public java.lang.Integer getType() {
		return get("type");
	}

	public void setUnitid(java.lang.Long unitid) {
		set("unitid", unitid);
	}

	public java.lang.Long getUnitid() {
		return get("unitid");
	}

	public void setVmcustomerid(java.lang.Long vmcustomerid) {
		set("vmcustomerid", vmcustomerid);
	}

	public java.lang.Long getVmcustomerid() {
		return get("vmcustomerid");
	}

	public void setMachineid(java.lang.String machineid) {
		set("machineid", machineid);
	}

	public java.lang.String getMachineid() {
		return get("machineid");
	}

	public void setProductsid(java.lang.String productsid) {
		set("productsid", productsid);
	}

	public java.lang.String getProductsid() {
		return get("productsid");
	}

	public void setUsername(java.lang.String username) {
		set("username", username);
	}

	public java.lang.String getUsername() {
		return get("username");
	}

}
