package com.jfinal.weixin.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseAppLastestversion<M extends BaseAppLastestversion<M>> extends Model<M> implements IBean {

	public void setMobilepfname(java.lang.String mobilepfname) {
		set("mobilepfname", mobilepfname);
	}

	public java.lang.String getMobilepfname() {
		return get("mobilepfname");
	}

	public void setVersion(java.lang.Integer version) {
		set("version", version);
	}

	public java.lang.Integer getVersion() {
		return get("version");
	}

	public void setDlurl(java.lang.String dlurl) {
		set("dlurl", dlurl);
	}

	public java.lang.String getDlurl() {
		return get("dlurl");
	}

	public void setForceupdateflag(java.lang.Integer forceupdateflag) {
		set("forceupdateflag", forceupdateflag);
	}

	public java.lang.Integer getForceupdateflag() {
		return get("forceupdateflag");
	}

	public void setAdddate(java.util.Date adddate) {
		set("adddate", adddate);
	}

	public java.util.Date getAdddate() {
		return get("adddate");
	}

}
