package com.jfinal.weixin.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseAppUsercoupon<M extends BaseAppUsercoupon<M>> extends Model<M> implements IBean {

	public void setUserid(java.lang.Long userid) {
		set("userid", userid);
	}

	public java.lang.Long getUserid() {
		return get("userid");
	}

	public void setCouponid(java.lang.Long couponid) {
		set("couponid", couponid);
	}

	public java.lang.Long getCouponid() {
		return get("couponid");
	}

	public void setUsedflag(java.lang.Integer usedflag) {
		set("usedflag", usedflag);
	}

	public java.lang.Integer getUsedflag() {
		return get("usedflag");
	}

	public void setUsedtime(java.util.Date usedtime) {
		set("usedtime", usedtime);
	}

	public java.util.Date getUsedtime() {
		return get("usedtime");
	}

}
