package com.jfinal.weixin.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseAndroidsetpara<M extends BaseAndroidsetpara<M>> extends Model<M> implements IBean {

	public void setDeviceid(java.lang.String deviceid) {
		set("deviceid", deviceid);
	}

	public java.lang.String getDeviceid() {
		return get("deviceid");
	}

	public void setVmcode(java.lang.String vmcode) {
		set("vmcode", vmcode);
	}

	public java.lang.String getVmcode() {
		return get("vmcode");
	}

	public void setVmname(java.lang.String vmname) {
		set("vmname", vmname);
	}

	public java.lang.String getVmname() {
		return get("vmname");
	}

	public void setIsapppermit(java.lang.Integer isapppermit) {
		set("isapppermit", isapppermit);
	}

	public java.lang.Integer getIsapppermit() {
		return get("isapppermit");
	}

	public void setIsconnectapp(java.lang.Integer isconnectapp) {
		set("isconnectapp", isconnectapp);
	}

	public java.lang.Integer getIsconnectapp() {
		return get("isconnectapp");
	}

	public void setCashfirst(java.lang.Integer cashfirst) {
		set("cashfirst", cashfirst);
	}

	public java.lang.Integer getCashfirst() {
		return get("cashfirst");
	}

	public void setJpushregid(java.lang.String jpushregid) {
		set("jpushregid", jpushregid);
	}

	public java.lang.String getJpushregid() {
		return get("jpushregid");
	}

	public void setMaskpwd(java.lang.String maskpwd) {
		set("maskpwd", maskpwd);
	}

	public java.lang.String getMaskpwd() {
		return get("maskpwd");
	}

	public void setHavedrink(java.lang.Integer havedrink) {
		set("havedrink", havedrink);
	}

	public java.lang.Integer getHavedrink() {
		return get("havedrink");
	}

	public void setHavedrinkhotcold(java.lang.Integer havedrinkhotcold) {
		set("havedrinkhotcold", havedrinkhotcold);
	}

	public java.lang.Integer getHavedrinkhotcold() {
		return get("havedrinkhotcold");
	}

	public void setNeedredline(java.lang.Integer needredline) {
		set("needredline", needredline);
	}

	public java.lang.Integer getNeedredline() {
		return get("needredline");
	}

	public void setIsfilelog(java.lang.Integer isfilelog) {
		set("isfilelog", isfilelog);
	}

	public java.lang.Integer getIsfilelog() {
		return get("isfilelog");
	}

	public void setSalecountclasttime(java.lang.String salecountclasttime) {
		set("salecountclasttime", salecountclasttime);
	}

	public java.lang.String getSalecountclasttime() {
		return get("salecountclasttime");
	}

	public void setCabinetnum(java.lang.Integer cabinetnum) {
		set("cabinetnum", cabinetnum);
	}

	public java.lang.Integer getCabinetnum() {
		return get("cabinetnum");
	}

	public void setCabineta(java.lang.Integer cabineta) {
		set("cabineta", cabineta);
	}

	public java.lang.Integer getCabineta() {
		return get("cabineta");
	}

	public void setCabinetb(java.lang.Integer cabinetb) {
		set("cabinetb", cabinetb);
	}

	public java.lang.Integer getCabinetb() {
		return get("cabinetb");
	}

	public void setCabinetc(java.lang.Integer cabinetc) {
		set("cabinetc", cabinetc);
	}

	public java.lang.Integer getCabinetc() {
		return get("cabinetc");
	}

	public void setCabinetd(java.lang.Integer cabinetd) {
		set("cabinetd", cabinetd);
	}

	public java.lang.Integer getCabinetd() {
		return get("cabinetd");
	}

	public void setCabinete(java.lang.Integer cabinete) {
		set("cabinete", cabinete);
	}

	public java.lang.Integer getCabinete() {
		return get("cabinete");
	}

	public void setHzcitydiscount(java.lang.Integer hzcitydiscount) {
		set("hzcitydiscount", hzcitydiscount);
	}

	public java.lang.Integer getHzcitydiscount() {
		return get("hzcitydiscount");
	}

	public void setZajiid(java.lang.String zajiid) {
		set("zajiid", zajiid);
	}

	public java.lang.String getZajiid() {
		return get("zajiid");
	}

	public void setPosid(java.lang.String posid) {
		set("posid", posid);
	}

	public java.lang.String getPosid() {
		return get("posid");
	}

	public void setIccardname(java.lang.String iccardname) {
		set("iccardname", iccardname);
	}

	public java.lang.String getIccardname() {
		return get("iccardname");
	}

	public void setAlipaypara(java.lang.String alipaypara) {
		set("alipaypara", alipaypara);
	}

	public java.lang.String getAlipaypara() {
		return get("alipaypara");
	}

	public void setWeixinpara(java.lang.String weixinpara) {
		set("weixinpara", weixinpara);
	}

	public java.lang.String getWeixinpara() {
		return get("weixinpara");
	}

	public void setYipaypara(java.lang.String yipaypara) {
		set("yipaypara", yipaypara);
	}

	public java.lang.String getYipaypara() {
		return get("yipaypara");
	}

	public void setBaidupara(java.lang.String baidupara) {
		set("baidupara", baidupara);
	}

	public java.lang.String getBaidupara() {
		return get("baidupara");
	}

	public void setIsexchange(java.lang.Integer isexchange) {
		set("isexchange", isexchange);
	}

	public java.lang.Integer getIsexchange() {
		return get("isexchange");
	}

	public void setUpdownhave(java.lang.Integer updownhave) {
		set("updownhave", updownhave);
	}

	public java.lang.Integer getUpdownhave() {
		return get("updownhave");
	}

	public void setIsnum(java.lang.Integer isnum) {
		set("isnum", isnum);
	}

	public java.lang.Integer getIsnum() {
		return get("isnum");
	}

	public void setEscowmoney(java.lang.Integer escowmoney) {
		set("escowmoney", escowmoney);
	}

	public java.lang.Integer getEscowmoney() {
		return get("escowmoney");
	}

	public void setLevelhigh(java.lang.String levelhigh) {
		set("levelhigh", levelhigh);
	}

	public java.lang.String getLevelhigh() {
		return get("levelhigh");
	}

	public void setTrackfloor(java.lang.Integer trackfloor) {
		set("trackfloor", trackfloor);
	}

	public java.lang.Integer getTrackfloor() {
		return get("trackfloor");
	}

	public void setEveryfloortracknumka(java.lang.Integer everyfloortracknumka) {
		set("everyfloortracknumka", everyfloortracknumka);
	}

	public java.lang.Integer getEveryfloortracknumka() {
		return get("everyfloortracknumka");
	}

	public void setEveryfloortracknum1(java.lang.Integer everyfloortracknum1) {
		set("everyfloortracknum1", everyfloortracknum1);
	}

	public java.lang.Integer getEveryfloortracknum1() {
		return get("everyfloortracknum1");
	}

	public void setEveryfloortracknum2(java.lang.Integer everyfloortracknum2) {
		set("everyfloortracknum2", everyfloortracknum2);
	}

	public java.lang.Integer getEveryfloortracknum2() {
		return get("everyfloortracknum2");
	}

	public void setEveryfloortracknum3(java.lang.Integer everyfloortracknum3) {
		set("everyfloortracknum3", everyfloortracknum3);
	}

	public java.lang.Integer getEveryfloortracknum3() {
		return get("everyfloortracknum3");
	}

	public void setEveryfloortracknum4(java.lang.Integer everyfloortracknum4) {
		set("everyfloortracknum4", everyfloortracknum4);
	}

	public java.lang.Integer getEveryfloortracknum4() {
		return get("everyfloortracknum4");
	}

	public void setEveryfloortracknum5(java.lang.Integer everyfloortracknum5) {
		set("everyfloortracknum5", everyfloortracknum5);
	}

	public java.lang.Integer getEveryfloortracknum5() {
		return get("everyfloortracknum5");
	}

	public void setEveryfloortracknum6(java.lang.Integer everyfloortracknum6) {
		set("everyfloortracknum6", everyfloortracknum6);
	}

	public java.lang.Integer getEveryfloortracknum6() {
		return get("everyfloortracknum6");
	}

	public void setEveryfloortracknum7(java.lang.Integer everyfloortracknum7) {
		set("everyfloortracknum7", everyfloortracknum7);
	}

	public java.lang.Integer getEveryfloortracknum7() {
		return get("everyfloortracknum7");
	}

	public void setUpdatetime(java.util.Date updatetime) {
		set("updatetime", updatetime);
	}

	public java.util.Date getUpdatetime() {
		return get("updatetime");
	}

	public void setPlace(java.lang.String place) {
		set("place", place);
	}

	public java.lang.String getPlace() {
		return get("place");
	}

	public void setLongitude(java.lang.Double longitude) {
		set("longitude", longitude);
	}

	public java.lang.Double getLongitude() {
		return get("longitude");
	}

	public void setLatitude(java.lang.Double latitude) {
		set("latitude", latitude);
	}

	public java.lang.Double getLatitude() {
		return get("latitude");
	}

}
