package com.jfinal.weixin.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseAndroidcoffee<M extends BaseAndroidcoffee<M>> extends Model<M> implements IBean {

	public void setDeviceid(java.lang.String deviceid) {
		set("deviceid", deviceid);
	}

	public java.lang.String getDeviceid() {
		return get("deviceid");
	}

	public void setVmname(java.lang.String vmname) {
		set("vmname", vmname);
	}

	public java.lang.String getVmname() {
		return get("vmname");
	}

	public void setType(java.lang.Integer type) {
		set("type", type);
	}

	public java.lang.Integer getType() {
		return get("type");
	}

	public void setIscash(java.lang.Integer iscash) {
		set("iscash", iscash);
	}

	public java.lang.Integer getIscash() {
		return get("iscash");
	}

	public void setIsalipay(java.lang.Integer isalipay) {
		set("isalipay", isalipay);
	}

	public java.lang.Integer getIsalipay() {
		return get("isalipay");
	}

	public void setIsweixin(java.lang.Integer isweixin) {
		set("isweixin", isweixin);
	}

	public java.lang.Integer getIsweixin() {
		return get("isweixin");
	}

	public void setBillstatus(java.lang.String billstatus) {
		set("billstatus", billstatus);
	}

	public java.lang.String getBillstatus() {
		return get("billstatus");
	}

	public void setCoinstatus(java.lang.String coinstatus) {
		set("coinstatus", coinstatus);
	}

	public java.lang.String getCoinstatus() {
		return get("coinstatus");
	}

	public void setOneyuannum(java.lang.Integer oneyuannum) {
		set("oneyuannum", oneyuannum);
	}

	public java.lang.Integer getOneyuannum() {
		return get("oneyuannum");
	}

	public void setFivejiaonum(java.lang.Integer fivejiaonum) {
		set("fivejiaonum", fivejiaonum);
	}

	public java.lang.Integer getFivejiaonum() {
		return get("fivejiaonum");
	}

	public void setErrorstr(java.lang.String errorstr) {
		set("errorstr", errorstr);
	}

	public java.lang.String getErrorstr() {
		return get("errorstr");
	}

	public void setFold1name(java.lang.String fold1name) {
		set("fold1name", fold1name);
	}

	public java.lang.String getFold1name() {
		return get("fold1name");
	}

	public void setFold2name(java.lang.String fold2name) {
		set("fold2name", fold2name);
	}

	public java.lang.String getFold2name() {
		return get("fold2name");
	}

	public void setFold3name(java.lang.String fold3name) {
		set("fold3name", fold3name);
	}

	public java.lang.String getFold3name() {
		return get("fold3name");
	}

	public void setFold4name(java.lang.String fold4name) {
		set("fold4name", fold4name);
	}

	public java.lang.String getFold4name() {
		return get("fold4name");
	}

	public void setFold5name(java.lang.String fold5name) {
		set("fold5name", fold5name);
	}

	public java.lang.String getFold5name() {
		return get("fold5name");
	}

	public void setReadypowder(java.lang.Integer readypowder) {
		set("readypowder", readypowder);
	}

	public java.lang.Integer getReadypowder() {
		return get("readypowder");
	}

	public void setCoffeetemp(java.lang.Integer coffeetemp) {
		set("coffeetemp", coffeetemp);
	}

	public java.lang.Integer getCoffeetemp() {
		return get("coffeetemp");
	}

	public void setKeeptemp(java.lang.Integer keeptemp) {
		set("keeptemp", keeptemp);
	}

	public java.lang.Integer getKeeptemp() {
		return get("keeptemp");
	}

	public void setAutoclean(java.lang.Integer autoclean) {
		set("autoclean", autoclean);
	}

	public java.lang.Integer getAutoclean() {
		return get("autoclean");
	}

	public void setAutocleanbean(java.lang.Integer autocleanbean) {
		set("autocleanbean", autocleanbean);
	}

	public java.lang.Integer getAutocleanbean() {
		return get("autocleanbean");
	}

	public void setAutocleaninstant(java.lang.Integer autocleaninstant) {
		set("autocleaninstant", autocleaninstant);
	}

	public java.lang.Integer getAutocleaninstant() {
		return get("autocleaninstant");
	}

	public void setCoffee1is(java.lang.Integer coffee1is) {
		set("coffee1is", coffee1is);
	}

	public java.lang.Integer getCoffee1is() {
		return get("coffee1is");
	}

	public void setCoffee1name(java.lang.String coffee1name) {
		set("coffee1name", coffee1name);
	}

	public java.lang.String getCoffee1name() {
		return get("coffee1name");
	}

	public void setCoffee1price(java.lang.String coffee1price) {
		set("coffee1price", coffee1price);
	}

	public java.lang.String getCoffee1price() {
		return get("coffee1price");
	}

	public void setTech1(java.lang.String tech1) {
		set("tech1", tech1);
	}

	public java.lang.String getTech1() {
		return get("tech1");
	}

	public void setTech1detail(java.lang.String tech1detail) {
		set("tech1detail", tech1detail);
	}

	public java.lang.String getTech1detail() {
		return get("tech1detail");
	}

	public void setCupsugar1(java.lang.String cupsugar1) {
		set("cupsugar1", cupsugar1);
	}

	public java.lang.String getCupsugar1() {
		return get("cupsugar1");
	}

	public void setCoffee2is(java.lang.Integer coffee2is) {
		set("coffee2is", coffee2is);
	}

	public java.lang.Integer getCoffee2is() {
		return get("coffee2is");
	}

	public void setCoffee2name(java.lang.String coffee2name) {
		set("coffee2name", coffee2name);
	}

	public java.lang.String getCoffee2name() {
		return get("coffee2name");
	}

	public void setCoffee2price(java.lang.String coffee2price) {
		set("coffee2price", coffee2price);
	}

	public java.lang.String getCoffee2price() {
		return get("coffee2price");
	}

	public void setTech2(java.lang.String tech2) {
		set("tech2", tech2);
	}

	public java.lang.String getTech2() {
		return get("tech2");
	}

	public void setTech2detail(java.lang.String tech2detail) {
		set("tech2detail", tech2detail);
	}

	public java.lang.String getTech2detail() {
		return get("tech2detail");
	}

	public void setCupsugar2(java.lang.String cupsugar2) {
		set("cupsugar2", cupsugar2);
	}

	public java.lang.String getCupsugar2() {
		return get("cupsugar2");
	}

	public void setCoffee3is(java.lang.Integer coffee3is) {
		set("coffee3is", coffee3is);
	}

	public java.lang.Integer getCoffee3is() {
		return get("coffee3is");
	}

	public void setCoffee3name(java.lang.String coffee3name) {
		set("coffee3name", coffee3name);
	}

	public java.lang.String getCoffee3name() {
		return get("coffee3name");
	}

	public void setCoffee3price(java.lang.String coffee3price) {
		set("coffee3price", coffee3price);
	}

	public java.lang.String getCoffee3price() {
		return get("coffee3price");
	}

	public void setTech3(java.lang.String tech3) {
		set("tech3", tech3);
	}

	public java.lang.String getTech3() {
		return get("tech3");
	}

	public void setTech3detail(java.lang.String tech3detail) {
		set("tech3detail", tech3detail);
	}

	public java.lang.String getTech3detail() {
		return get("tech3detail");
	}

	public void setCupsugar3(java.lang.String cupsugar3) {
		set("cupsugar3", cupsugar3);
	}

	public java.lang.String getCupsugar3() {
		return get("cupsugar3");
	}

	public void setCoffee4is(java.lang.Integer coffee4is) {
		set("coffee4is", coffee4is);
	}

	public java.lang.Integer getCoffee4is() {
		return get("coffee4is");
	}

	public void setCoffee4name(java.lang.String coffee4name) {
		set("coffee4name", coffee4name);
	}

	public java.lang.String getCoffee4name() {
		return get("coffee4name");
	}

	public void setCoffee4price(java.lang.String coffee4price) {
		set("coffee4price", coffee4price);
	}

	public java.lang.String getCoffee4price() {
		return get("coffee4price");
	}

	public void setTech4(java.lang.String tech4) {
		set("tech4", tech4);
	}

	public java.lang.String getTech4() {
		return get("tech4");
	}

	public void setTech4detail(java.lang.String tech4detail) {
		set("tech4detail", tech4detail);
	}

	public java.lang.String getTech4detail() {
		return get("tech4detail");
	}

	public void setCupsugar4(java.lang.String cupsugar4) {
		set("cupsugar4", cupsugar4);
	}

	public java.lang.String getCupsugar4() {
		return get("cupsugar4");
	}

	public void setCoffee5is(java.lang.Integer coffee5is) {
		set("coffee5is", coffee5is);
	}

	public java.lang.Integer getCoffee5is() {
		return get("coffee5is");
	}

	public void setCoffee5name(java.lang.String coffee5name) {
		set("coffee5name", coffee5name);
	}

	public java.lang.String getCoffee5name() {
		return get("coffee5name");
	}

	public void setCoffee5price(java.lang.String coffee5price) {
		set("coffee5price", coffee5price);
	}

	public java.lang.String getCoffee5price() {
		return get("coffee5price");
	}

	public void setTech5(java.lang.String tech5) {
		set("tech5", tech5);
	}

	public java.lang.String getTech5() {
		return get("tech5");
	}

	public void setTech5detail(java.lang.String tech5detail) {
		set("tech5detail", tech5detail);
	}

	public java.lang.String getTech5detail() {
		return get("tech5detail");
	}

	public void setCupsugar5(java.lang.String cupsugar5) {
		set("cupsugar5", cupsugar5);
	}

	public java.lang.String getCupsugar5() {
		return get("cupsugar5");
	}

	public void setCoffee6is(java.lang.Integer coffee6is) {
		set("coffee6is", coffee6is);
	}

	public java.lang.Integer getCoffee6is() {
		return get("coffee6is");
	}

	public void setCoffee6name(java.lang.String coffee6name) {
		set("coffee6name", coffee6name);
	}

	public java.lang.String getCoffee6name() {
		return get("coffee6name");
	}

	public void setCoffee6price(java.lang.String coffee6price) {
		set("coffee6price", coffee6price);
	}

	public java.lang.String getCoffee6price() {
		return get("coffee6price");
	}

	public void setTech6(java.lang.String tech6) {
		set("tech6", tech6);
	}

	public java.lang.String getTech6() {
		return get("tech6");
	}

	public void setTech6detail(java.lang.String tech6detail) {
		set("tech6detail", tech6detail);
	}

	public java.lang.String getTech6detail() {
		return get("tech6detail");
	}

	public void setCupsugar6(java.lang.String cupsugar6) {
		set("cupsugar6", cupsugar6);
	}

	public java.lang.String getCupsugar6() {
		return get("cupsugar6");
	}

	public void setCoffee7is(java.lang.Integer coffee7is) {
		set("coffee7is", coffee7is);
	}

	public java.lang.Integer getCoffee7is() {
		return get("coffee7is");
	}

	public void setCoffee7name(java.lang.String coffee7name) {
		set("coffee7name", coffee7name);
	}

	public java.lang.String getCoffee7name() {
		return get("coffee7name");
	}

	public void setCoffee7price(java.lang.String coffee7price) {
		set("coffee7price", coffee7price);
	}

	public java.lang.String getCoffee7price() {
		return get("coffee7price");
	}

	public void setTech7(java.lang.String tech7) {
		set("tech7", tech7);
	}

	public java.lang.String getTech7() {
		return get("tech7");
	}

	public void setTech7detail(java.lang.String tech7detail) {
		set("tech7detail", tech7detail);
	}

	public java.lang.String getTech7detail() {
		return get("tech7detail");
	}

	public void setCupsugar7(java.lang.String cupsugar7) {
		set("cupsugar7", cupsugar7);
	}

	public java.lang.String getCupsugar7() {
		return get("cupsugar7");
	}

	public void setCoffee8is(java.lang.Integer coffee8is) {
		set("coffee8is", coffee8is);
	}

	public java.lang.Integer getCoffee8is() {
		return get("coffee8is");
	}

	public void setCoffee8name(java.lang.String coffee8name) {
		set("coffee8name", coffee8name);
	}

	public java.lang.String getCoffee8name() {
		return get("coffee8name");
	}

	public void setCoffee8price(java.lang.String coffee8price) {
		set("coffee8price", coffee8price);
	}

	public java.lang.String getCoffee8price() {
		return get("coffee8price");
	}

	public void setTech8(java.lang.String tech8) {
		set("tech8", tech8);
	}

	public java.lang.String getTech8() {
		return get("tech8");
	}

	public void setTech8detail(java.lang.String tech8detail) {
		set("tech8detail", tech8detail);
	}

	public java.lang.String getTech8detail() {
		return get("tech8detail");
	}

	public void setCupsugar8(java.lang.String cupsugar8) {
		set("cupsugar8", cupsugar8);
	}

	public java.lang.String getCupsugar8() {
		return get("cupsugar8");
	}

	public void setCoffee9is(java.lang.Integer coffee9is) {
		set("coffee9is", coffee9is);
	}

	public java.lang.Integer getCoffee9is() {
		return get("coffee9is");
	}

	public void setCoffee9name(java.lang.String coffee9name) {
		set("coffee9name", coffee9name);
	}

	public java.lang.String getCoffee9name() {
		return get("coffee9name");
	}

	public void setCoffee9price(java.lang.String coffee9price) {
		set("coffee9price", coffee9price);
	}

	public java.lang.String getCoffee9price() {
		return get("coffee9price");
	}

	public void setTech9(java.lang.String tech9) {
		set("tech9", tech9);
	}

	public java.lang.String getTech9() {
		return get("tech9");
	}

	public void setTech9detail(java.lang.String tech9detail) {
		set("tech9detail", tech9detail);
	}

	public java.lang.String getTech9detail() {
		return get("tech9detail");
	}

	public void setCupsugar9(java.lang.String cupsugar9) {
		set("cupsugar9", cupsugar9);
	}

	public java.lang.String getCupsugar9() {
		return get("cupsugar9");
	}

	public void setCoffee10is(java.lang.Integer coffee10is) {
		set("coffee10is", coffee10is);
	}

	public java.lang.Integer getCoffee10is() {
		return get("coffee10is");
	}

	public void setCoffee10name(java.lang.String coffee10name) {
		set("coffee10name", coffee10name);
	}

	public java.lang.String getCoffee10name() {
		return get("coffee10name");
	}

	public void setCoffee10price(java.lang.String coffee10price) {
		set("coffee10price", coffee10price);
	}

	public java.lang.String getCoffee10price() {
		return get("coffee10price");
	}

	public void setTech10(java.lang.String tech10) {
		set("tech10", tech10);
	}

	public java.lang.String getTech10() {
		return get("tech10");
	}

	public void setTech10detail(java.lang.String tech10detail) {
		set("tech10detail", tech10detail);
	}

	public java.lang.String getTech10detail() {
		return get("tech10detail");
	}

	public void setCupsugar10(java.lang.String cupsugar10) {
		set("cupsugar10", cupsugar10);
	}

	public java.lang.String getCupsugar10() {
		return get("cupsugar10");
	}

	public void setCoffee11is(java.lang.Integer coffee11is) {
		set("coffee11is", coffee11is);
	}

	public java.lang.Integer getCoffee11is() {
		return get("coffee11is");
	}

	public void setCoffee11name(java.lang.String coffee11name) {
		set("coffee11name", coffee11name);
	}

	public java.lang.String getCoffee11name() {
		return get("coffee11name");
	}

	public void setCoffee11price(java.lang.String coffee11price) {
		set("coffee11price", coffee11price);
	}

	public java.lang.String getCoffee11price() {
		return get("coffee11price");
	}

	public void setTech11(java.lang.String tech11) {
		set("tech11", tech11);
	}

	public java.lang.String getTech11() {
		return get("tech11");
	}

	public void setTech11detail(java.lang.String tech11detail) {
		set("tech11detail", tech11detail);
	}

	public java.lang.String getTech11detail() {
		return get("tech11detail");
	}

	public void setCupsugar11(java.lang.String cupsugar11) {
		set("cupsugar11", cupsugar11);
	}

	public java.lang.String getCupsugar11() {
		return get("cupsugar11");
	}

	public void setCoffee12is(java.lang.Integer coffee12is) {
		set("coffee12is", coffee12is);
	}

	public java.lang.Integer getCoffee12is() {
		return get("coffee12is");
	}

	public void setCoffee12name(java.lang.String coffee12name) {
		set("coffee12name", coffee12name);
	}

	public java.lang.String getCoffee12name() {
		return get("coffee12name");
	}

	public void setCoffee12price(java.lang.String coffee12price) {
		set("coffee12price", coffee12price);
	}

	public java.lang.String getCoffee12price() {
		return get("coffee12price");
	}

	public void setTech12(java.lang.String tech12) {
		set("tech12", tech12);
	}

	public java.lang.String getTech12() {
		return get("tech12");
	}

	public void setTech12detail(java.lang.String tech12detail) {
		set("tech12detail", tech12detail);
	}

	public java.lang.String getTech12detail() {
		return get("tech12detail");
	}

	public void setCupsugar12(java.lang.String cupsugar12) {
		set("cupsugar12", cupsugar12);
	}

	public java.lang.String getCupsugar12() {
		return get("cupsugar12");
	}

	public void setCoffee13is(java.lang.Integer coffee13is) {
		set("coffee13is", coffee13is);
	}

	public java.lang.Integer getCoffee13is() {
		return get("coffee13is");
	}

	public void setCoffee13name(java.lang.String coffee13name) {
		set("coffee13name", coffee13name);
	}

	public java.lang.String getCoffee13name() {
		return get("coffee13name");
	}

	public void setCoffee13price(java.lang.String coffee13price) {
		set("coffee13price", coffee13price);
	}

	public java.lang.String getCoffee13price() {
		return get("coffee13price");
	}

	public void setTech13(java.lang.String tech13) {
		set("tech13", tech13);
	}

	public java.lang.String getTech13() {
		return get("tech13");
	}

	public void setTech13detail(java.lang.String tech13detail) {
		set("tech13detail", tech13detail);
	}

	public java.lang.String getTech13detail() {
		return get("tech13detail");
	}

	public void setCupsugar13(java.lang.String cupsugar13) {
		set("cupsugar13", cupsugar13);
	}

	public java.lang.String getCupsugar13() {
		return get("cupsugar13");
	}

	public void setCoffee14is(java.lang.Integer coffee14is) {
		set("coffee14is", coffee14is);
	}

	public java.lang.Integer getCoffee14is() {
		return get("coffee14is");
	}

	public void setCoffee14name(java.lang.String coffee14name) {
		set("coffee14name", coffee14name);
	}

	public java.lang.String getCoffee14name() {
		return get("coffee14name");
	}

	public void setCoffee14price(java.lang.String coffee14price) {
		set("coffee14price", coffee14price);
	}

	public java.lang.String getCoffee14price() {
		return get("coffee14price");
	}

	public void setTech14(java.lang.String tech14) {
		set("tech14", tech14);
	}

	public java.lang.String getTech14() {
		return get("tech14");
	}

	public void setTech14detail(java.lang.String tech14detail) {
		set("tech14detail", tech14detail);
	}

	public java.lang.String getTech14detail() {
		return get("tech14detail");
	}

	public void setCupsugar14(java.lang.String cupsugar14) {
		set("cupsugar14", cupsugar14);
	}

	public java.lang.String getCupsugar14() {
		return get("cupsugar14");
	}

	public void setCoffee15is(java.lang.Integer coffee15is) {
		set("coffee15is", coffee15is);
	}

	public java.lang.Integer getCoffee15is() {
		return get("coffee15is");
	}

	public void setCoffee15name(java.lang.String coffee15name) {
		set("coffee15name", coffee15name);
	}

	public java.lang.String getCoffee15name() {
		return get("coffee15name");
	}

	public void setCoffee15price(java.lang.String coffee15price) {
		set("coffee15price", coffee15price);
	}

	public java.lang.String getCoffee15price() {
		return get("coffee15price");
	}

	public void setTech15(java.lang.String tech15) {
		set("tech15", tech15);
	}

	public java.lang.String getTech15() {
		return get("tech15");
	}

	public void setTech15detail(java.lang.String tech15detail) {
		set("tech15detail", tech15detail);
	}

	public java.lang.String getTech15detail() {
		return get("tech15detail");
	}

	public void setCupsugar15(java.lang.String cupsugar15) {
		set("cupsugar15", cupsugar15);
	}

	public java.lang.String getCupsugar15() {
		return get("cupsugar15");
	}

	public void setCoffee16is(java.lang.Integer coffee16is) {
		set("coffee16is", coffee16is);
	}

	public java.lang.Integer getCoffee16is() {
		return get("coffee16is");
	}

	public void setCoffee16name(java.lang.String coffee16name) {
		set("coffee16name", coffee16name);
	}

	public java.lang.String getCoffee16name() {
		return get("coffee16name");
	}

	public void setCoffee16price(java.lang.String coffee16price) {
		set("coffee16price", coffee16price);
	}

	public java.lang.String getCoffee16price() {
		return get("coffee16price");
	}

	public void setTech16(java.lang.String tech16) {
		set("tech16", tech16);
	}

	public java.lang.String getTech16() {
		return get("tech16");
	}

	public void setTech16detail(java.lang.String tech16detail) {
		set("tech16detail", tech16detail);
	}

	public java.lang.String getTech16detail() {
		return get("tech16detail");
	}

	public void setCupsugar16(java.lang.String cupsugar16) {
		set("cupsugar16", cupsugar16);
	}

	public java.lang.String getCupsugar16() {
		return get("cupsugar16");
	}

	public void setLongitude(java.lang.Double longitude) {
		set("longitude", longitude);
	}

	public java.lang.Double getLongitude() {
		return get("longitude");
	}

	public void setLatitude(java.lang.Double latitude) {
		set("latitude", latitude);
	}

	public java.lang.Double getLatitude() {
		return get("latitude");
	}

	public void setUpdatetime(java.util.Date updatetime) {
		set("updatetime", updatetime);
	}

	public java.util.Date getUpdatetime() {
		return get("updatetime");
	}

	public void setPlace(java.lang.String place) {
		set("place", place);
	}

	public java.lang.String getPlace() {
		return get("place");
	}

}
