package com.jfinal.weixin.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseAppUsermoneyrecord<M extends BaseAppUsermoneyrecord<M>> extends Model<M> implements IBean {

	public void setMoneyrecordid(java.math.BigInteger moneyrecordid) {
		set("moneyrecordid", moneyrecordid);
	}

	public java.math.BigInteger getMoneyrecordid() {
		return get("moneyrecordid");
	}

	public void setUserid(java.lang.Long userid) {
		set("userid", userid);
	}

	public java.lang.Long getUserid() {
		return get("userid");
	}

	public void setType(java.lang.String type) {
		set("type", type);
	}

	public java.lang.String getType() {
		return get("type");
	}

	public void setConnectid(java.lang.Long connectid) {
		set("connectid", connectid);
	}

	public java.lang.Long getConnectid() {
		return get("connectid");
	}

	public void setInserttime(java.util.Date inserttime) {
		set("inserttime", inserttime);
	}

	public java.util.Date getInserttime() {
		return get("inserttime");
	}

	public void setChangemoney(java.math.BigDecimal changemoney) {
		set("changemoney", changemoney);
	}

	public java.math.BigDecimal getChangemoney() {
		return get("changemoney");
	}

	public void setBeforemoney(java.math.BigDecimal beforemoney) {
		set("beforemoney", beforemoney);
	}

	public java.math.BigDecimal getBeforemoney() {
		return get("beforemoney");
	}

	public void setAftermoney(java.math.BigDecimal aftermoney) {
		set("aftermoney", aftermoney);
	}

	public java.math.BigDecimal getAftermoney() {
		return get("aftermoney");
	}

}
