package com.jfinal.weixin.base;

import com.jfinal.plugin.activerecord.IBean;
import com.jfinal.plugin.activerecord.Model;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseUser<M extends BaseUser<M>> extends Model<M> implements IBean {

	public void setId(java.lang.String id) {
		set("id", id);
	}

	public java.lang.String getId() {
		return get("id");
	}

	public void setOpenId(java.lang.String openId) {
		set("open_id", openId);
	}

	public java.lang.String getOpenId() {
		return get("open_id");
	}

	public void setUsername(java.lang.String username) {
		set("username", username);
	}

	public java.lang.String getUsername() {
		return get("username");
	}

	public void setMobile(java.lang.String mobile) {
		set("mobile", mobile);
	}

	public java.lang.String getMobile() {
		return get("mobile");
	}

	public void setPassword(java.lang.String password) {
		set("password", password);
	}

	public java.lang.String getPassword() {
		return get("password");
	}

	public void setSex(java.lang.Integer sex) {
		set("sex", sex);
	}

	public java.lang.Integer getSex() {
		return get("sex");
	}

	public void setImagePath(java.lang.String imagePath) {
		set("image_path", imagePath);
	}

	public java.lang.String getImagePath() {
		return get("image_path");
	}

	public void setHospitalId(java.lang.Integer hospitalId) {
		set("hospital_id", hospitalId);
	}

	public java.lang.Integer getHospitalId() {
		return get("hospital_id");
	}

	public void setDepartmentId(java.lang.Integer departmentId) {
		set("department_id", departmentId);
	}

	public java.lang.Integer getDepartmentId() {
		return get("department_id");
	}

	public void setTitleId(java.lang.Integer titleId) {
		set("title_id", titleId);
	}

	public java.lang.Integer getTitleId() {
		return get("title_id");
	}

	public void setDescription(java.lang.String description) {
		set("description", description);
	}

	public java.lang.String getDescription() {
		return get("description");
	}

	public void setAddressProvinceId(java.lang.Integer addressProvinceId) {
		set("address_province_id", addressProvinceId);
	}

	public java.lang.Integer getAddressProvinceId() {
		return get("address_province_id");
	}

	public void setAddressCityId(java.lang.Integer addressCityId) {
		set("address_city_Id", addressCityId);
	}

	public java.lang.Integer getAddressCityId() {
		return get("address_city_Id");
	}

	public void setAddressRegionId(java.lang.Integer addressRegionId) {
		set("address_region_Id", addressRegionId);
	}

	public java.lang.Integer getAddressRegionId() {
		return get("address_region_Id");
	}

	public void setAuthedFlag(java.lang.Integer authedFlag) {
		set("authed_flag", authedFlag);
	}

	public java.lang.Integer getAuthedFlag() {
		return get("authed_flag");
	}

	public void setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
	}

	public java.util.Date getCreateTime() {
		return get("create_time");
	}

	public void setUpdateTime(java.util.Date updateTime) {
		set("update_time", updateTime);
	}

	public java.util.Date getUpdateTime() {
		return get("update_time");
	}

}
