package com.jfinal.weixin.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseIdVmunitrecord<M extends BaseIdVmunitrecord<M>> extends Model<M> implements IBean {

	public void setUnitrecordid(java.lang.Long unitrecordid) {
		set("unitrecordid", unitrecordid);
	}

	public java.lang.Long getUnitrecordid() {
		return get("unitrecordid");
	}

	public void setAddtime(java.util.Date addtime) {
		set("addtime", addtime);
	}

	public java.util.Date getAddtime() {
		return get("addtime");
	}

	public void setDescription(java.lang.String description) {
		set("description", description);
	}

	public java.lang.String getDescription() {
		return get("description");
	}

	public void setType(java.lang.Integer type) {
		set("type", type);
	}

	public java.lang.Integer getType() {
		return get("type");
	}

	public void setUnitbalance(java.lang.Double unitbalance) {
		set("unitbalance", unitbalance);
	}

	public java.lang.Double getUnitbalance() {
		return get("unitbalance");
	}

	public void setUnitcharge(java.lang.Double unitcharge) {
		set("unitcharge", unitcharge);
	}

	public java.lang.Double getUnitcharge() {
		return get("unitcharge");
	}

	public void setUnitid(java.lang.Long unitid) {
		set("unitid", unitid);
	}

	public java.lang.Long getUnitid() {
		return get("unitid");
	}

	public void setUpdaterealname(java.lang.String updaterealname) {
		set("updaterealname", updaterealname);
	}

	public java.lang.String getUpdaterealname() {
		return get("updaterealname");
	}

	public void setRelativeid(java.lang.Long relativeid) {
		set("relativeid", relativeid);
	}

	public java.lang.Long getRelativeid() {
		return get("relativeid");
	}

	public void setRelativetype(java.lang.Integer relativetype) {
		set("relativetype", relativetype);
	}

	public java.lang.Integer getRelativetype() {
		return get("relativetype");
	}

}
