package com.jfinal.weixin.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseWxidOpenidCardno<M extends BaseWxidOpenidCardno<M>> extends Model<M> implements IBean {

	public void setFanopenid(java.lang.String fanopenid) {
		set("fanopenid", fanopenid);
	}

	public java.lang.String getFanopenid() {
		return get("fanopenid");
	}

	public void setWxopenid(java.lang.String wxopenid) {
		set("wxopenid", wxopenid);
	}

	public java.lang.String getWxopenid() {
		return get("wxopenid");
	}

	public void setIdcardno(java.lang.String idcardno) {
		set("idcardno", idcardno);
	}

	public java.lang.String getIdcardno() {
		return get("idcardno");
	}

	public void setSubtime(java.util.Date subtime) {
		set("subtime", subtime);
	}

	public java.util.Date getSubtime() {
		return get("subtime");
	}

	public void setUnsubtime(java.util.Date unsubtime) {
		set("unsubtime", unsubtime);
	}

	public java.util.Date getUnsubtime() {
		return get("unsubtime");
	}

}
