package com.jfinal.weixin.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseAppMobilechkcode<M extends BaseAppMobilechkcode<M>> extends Model<M> implements IBean {

	public void setId(java.math.BigInteger id) {
		set("id", id);
	}

	public java.math.BigInteger getId() {
		return get("id");
	}

	public void setMobileno(java.lang.String mobileno) {
		set("mobileno", mobileno);
	}

	public java.lang.String getMobileno() {
		return get("mobileno");
	}

	public void setChkcode(java.lang.String chkcode) {
		set("chkcode", chkcode);
	}

	public java.lang.String getChkcode() {
		return get("chkcode");
	}

	public void setSendtime(java.util.Date sendtime) {
		set("sendtime", sendtime);
	}

	public java.util.Date getSendtime() {
		return get("sendtime");
	}

	public void setSendresult(java.lang.String sendresult) {
		set("sendresult", sendresult);
	}

	public java.lang.String getSendresult() {
		return get("sendresult");
	}

}
