package com.jfinal.weixin.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseAppPointexchange<M extends BaseAppPointexchange<M>> extends Model<M> implements IBean {

	public void setPointexid(java.math.BigInteger pointexid) {
		set("pointexid", pointexid);
	}

	public java.math.BigInteger getPointexid() {
		return get("pointexid");
	}

	public void setPointexname(java.lang.String pointexname) {
		set("pointexname", pointexname);
	}

	public java.lang.String getPointexname() {
		return get("pointexname");
	}

	public void setPointexphotourl(java.lang.String pointexphotourl) {
		set("pointexphotourl", pointexphotourl);
	}

	public java.lang.String getPointexphotourl() {
		return get("pointexphotourl");
	}

	public void setStartdate(java.util.Date startdate) {
		set("startdate", startdate);
	}

	public java.util.Date getStartdate() {
		return get("startdate");
	}

	public void setEnddate(java.util.Date enddate) {
		set("enddate", enddate);
	}

	public java.util.Date getEnddate() {
		return get("enddate");
	}

	public void setTotalcount(java.lang.Integer totalcount) {
		set("totalcount", totalcount);
	}

	public java.lang.Integer getTotalcount() {
		return get("totalcount");
	}

	public void setUsedcount(java.lang.Integer usedcount) {
		set("usedcount", usedcount);
	}

	public java.lang.Integer getUsedcount() {
		return get("usedcount");
	}

	public void setOneusermax(java.lang.Integer oneusermax) {
		set("oneusermax", oneusermax);
	}

	public java.lang.Integer getOneusermax() {
		return get("oneusermax");
	}

	public void setNeedpoint(java.lang.Integer needpoint) {
		set("needpoint", needpoint);
	}

	public java.lang.Integer getNeedpoint() {
		return get("needpoint");
	}

	public void setType(java.lang.String type) {
		set("type", type);
	}

	public java.lang.String getType() {
		return get("type");
	}

	public void setGoodname(java.lang.String goodname) {
		set("goodname", goodname);
	}

	public java.lang.String getGoodname() {
		return get("goodname");
	}

	public void setExmoney(java.math.BigDecimal exmoney) {
		set("exmoney", exmoney);
	}

	public java.math.BigDecimal getExmoney() {
		return get("exmoney");
	}

}
