package com.jfinal.weixin.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseAppUserpayok<M extends BaseAppUserpayok<M>> extends Model<M> implements IBean {

	public void setPayokid(java.math.BigInteger payokid) {
		set("payokid", payokid);
	}

	public java.math.BigInteger getPayokid() {
		return get("payokid");
	}

	public void setUserid(java.lang.Long userid) {
		set("userid", userid);
	}

	public java.lang.Long getUserid() {
		return get("userid");
	}

	public void setPayway(java.lang.String payway) {
		set("payway", payway);
	}

	public java.lang.String getPayway() {
		return get("payway");
	}

	public void setPaytransid(java.lang.String paytransid) {
		set("paytransid", paytransid);
	}

	public java.lang.String getPaytransid() {
		return get("paytransid");
	}

	public void setPaymoney(java.math.BigDecimal paymoney) {
		set("paymoney", paymoney);
	}

	public java.math.BigDecimal getPaymoney() {
		return get("paymoney");
	}

	public void setPayerid(java.lang.String payerid) {
		set("payerid", payerid);
	}

	public java.lang.String getPayerid() {
		return get("payerid");
	}

	public void setPayfor(java.lang.String payfor) {
		set("payfor", payfor);
	}

	public java.lang.String getPayfor() {
		return get("payfor");
	}

	public void setOwnerid(java.lang.String ownerid) {
		set("ownerid", ownerid);
	}

	public java.lang.String getOwnerid() {
		return get("ownerid");
	}

	public void setPaydate(java.util.Date paydate) {
		set("paydate", paydate);
	}

	public java.util.Date getPaydate() {
		return get("paydate");
	}

	public void setInserttime(java.util.Date inserttime) {
		set("inserttime", inserttime);
	}

	public java.util.Date getInserttime() {
		return get("inserttime");
	}

	public void setOuttransid(java.lang.String outtransid) {
		set("outtransid", outtransid);
	}

	public java.lang.String getOuttransid() {
		return get("outtransid");
	}

	public void setSellerEmail(java.lang.String sellerEmail) {
		set("seller_email", sellerEmail);
	}

	public java.lang.String getSellerEmail() {
		return get("seller_email");
	}

	public void setPaybackid(java.lang.Long paybackid) {
		set("paybackid", paybackid);
	}

	public java.lang.Long getPaybackid() {
		return get("paybackid");
	}

}
