package com.jfinal.weixin.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseWxidVmidWxopenid<M extends BaseWxidVmidWxopenid<M>> extends Model<M> implements IBean {

	public void setVmcustomerid(java.lang.Long vmcustomerid) {
		set("vmcustomerid", vmcustomerid);
	}

	public java.lang.Long getVmcustomerid() {
		return get("vmcustomerid");
	}

	public void setWxopenid(java.lang.String wxopenid) {
		set("wxopenid", wxopenid);
	}

	public java.lang.String getWxopenid() {
		return get("wxopenid");
	}

	public void setReadme(java.lang.String readme) {
		set("readme", readme);
	}

	public java.lang.String getReadme() {
		return get("readme");
	}

	public void setHttp(java.lang.String http) {
		set("http", http);
	}

	public java.lang.String getHttp() {
		return get("http");
	}

	public void setChargehttp(java.lang.String chargehttp) {
		set("chargehttp", chargehttp);
	}

	public java.lang.String getChargehttp() {
		return get("chargehttp");
	}

}
