package com.jfinal.weixin.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseAndroidguangone<M extends BaseAndroidguangone<M>> extends Model<M> implements IBean {

	public void setDeviceid(java.lang.String deviceid) {
		set("deviceid", deviceid);
	}

	public java.lang.String getDeviceid() {
		return get("deviceid");
	}

	public void setVmname(java.lang.String vmname) {
		set("vmname", vmname);
	}

	public java.lang.String getVmname() {
		return get("vmname");
	}

	public void setType(java.lang.Integer type) {
		set("type", type);
	}

	public java.lang.Integer getType() {
		return get("type");
	}

	public void setCoininstatus(java.lang.String coininstatus) {
		set("coininstatus", coininstatus);
	}

	public java.lang.String getCoininstatus() {
		return get("coininstatus");
	}

	public void setOneyuannum(java.lang.Integer oneyuannum) {
		set("oneyuannum", oneyuannum);
	}

	public java.lang.Integer getOneyuannum() {
		return get("oneyuannum");
	}

	public void setFivejiaonum(java.lang.Integer fivejiaonum) {
		set("fivejiaonum", fivejiaonum);
	}

	public java.lang.Integer getFivejiaonum() {
		return get("fivejiaonum");
	}

	public void setDoorstatus(java.lang.Integer doorstatus) {
		set("doorstatus", doorstatus);
	}

	public java.lang.Integer getDoorstatus() {
		return get("doorstatus");
	}

	public void setTempstatus(java.lang.Integer tempstatus) {
		set("tempstatus", tempstatus);
	}

	public java.lang.Integer getTempstatus() {
		return get("tempstatus");
	}

	public void setInsidetempnow(java.lang.Integer insidetempnow) {
		set("insidetempnow", insidetempnow);
	}

	public java.lang.Integer getInsidetempnow() {
		return get("insidetempnow");
	}

	public void setInsidetempset(java.lang.Integer insidetempset) {
		set("insidetempset", insidetempset);
	}

	public java.lang.Integer getInsidetempset() {
		return get("insidetempset");
	}

	public void setLefttempnow(java.lang.Integer lefttempnow) {
		set("lefttempnow", lefttempnow);
	}

	public java.lang.Integer getLefttempnow() {
		return get("lefttempnow");
	}

	public void setRighttempnow(java.lang.Integer righttempnow) {
		set("righttempnow", righttempnow);
	}

	public java.lang.Integer getRighttempnow() {
		return get("righttempnow");
	}

	public void setOutsidetempnow(java.lang.Integer outsidetempnow) {
		set("outsidetempnow", outsidetempnow);
	}

	public java.lang.Integer getOutsidetempnow() {
		return get("outsidetempnow");
	}

	public void setTracknum(java.lang.Integer tracknum) {
		set("tracknum", tracknum);
	}

	public java.lang.Integer getTracknum() {
		return get("tracknum");
	}

	public void setCabinetnum(java.lang.Integer cabinetnum) {
		set("cabinetnum", cabinetnum);
	}

	public java.lang.Integer getCabinetnum() {
		return get("cabinetnum");
	}

	public void setMingcheng01(java.lang.String mingcheng01) {
		set("mingcheng01", mingcheng01);
	}

	public java.lang.String getMingcheng01() {
		return get("mingcheng01");
	}

	public void setSprice01(java.lang.String sprice01) {
		set("sprice01", sprice01);
	}

	public java.lang.String getSprice01() {
		return get("sprice01");
	}

	public void setHavenow01(java.lang.Integer havenow01) {
		set("havenow01", havenow01);
	}

	public java.lang.Integer getHavenow01() {
		return get("havenow01");
	}

	public void setNow01(java.lang.Integer now01) {
		set("now01", now01);
	}

	public java.lang.Integer getNow01() {
		return get("now01");
	}

	public void setMax01(java.lang.Integer max01) {
		set("max01", max01);
	}

	public java.lang.Integer getMax01() {
		return get("max01");
	}

	public void setTrackstatus01(java.lang.Integer trackstatus01) {
		set("trackstatus01", trackstatus01);
	}

	public java.lang.Integer getTrackstatus01() {
		return get("trackstatus01");
	}

	public void setSerror01(java.lang.String serror01) {
		set("serror01", serror01);
	}

	public java.lang.String getSerror01() {
		return get("serror01");
	}

	public void setMingcheng02(java.lang.String mingcheng02) {
		set("mingcheng02", mingcheng02);
	}

	public java.lang.String getMingcheng02() {
		return get("mingcheng02");
	}

	public void setSprice02(java.lang.String sprice02) {
		set("sprice02", sprice02);
	}

	public java.lang.String getSprice02() {
		return get("sprice02");
	}

	public void setHavenow02(java.lang.Integer havenow02) {
		set("havenow02", havenow02);
	}

	public java.lang.Integer getHavenow02() {
		return get("havenow02");
	}

	public void setNow02(java.lang.Integer now02) {
		set("now02", now02);
	}

	public java.lang.Integer getNow02() {
		return get("now02");
	}

	public void setMax02(java.lang.Integer max02) {
		set("max02", max02);
	}

	public java.lang.Integer getMax02() {
		return get("max02");
	}

	public void setTrackstatus02(java.lang.Integer trackstatus02) {
		set("trackstatus02", trackstatus02);
	}

	public java.lang.Integer getTrackstatus02() {
		return get("trackstatus02");
	}

	public void setSerror02(java.lang.String serror02) {
		set("serror02", serror02);
	}

	public java.lang.String getSerror02() {
		return get("serror02");
	}

	public void setMingcheng03(java.lang.String mingcheng03) {
		set("mingcheng03", mingcheng03);
	}

	public java.lang.String getMingcheng03() {
		return get("mingcheng03");
	}

	public void setSprice03(java.lang.String sprice03) {
		set("sprice03", sprice03);
	}

	public java.lang.String getSprice03() {
		return get("sprice03");
	}

	public void setHavenow03(java.lang.Integer havenow03) {
		set("havenow03", havenow03);
	}

	public java.lang.Integer getHavenow03() {
		return get("havenow03");
	}

	public void setNow03(java.lang.Integer now03) {
		set("now03", now03);
	}

	public java.lang.Integer getNow03() {
		return get("now03");
	}

	public void setMax03(java.lang.Integer max03) {
		set("max03", max03);
	}

	public java.lang.Integer getMax03() {
		return get("max03");
	}

	public void setTrackstatus03(java.lang.Integer trackstatus03) {
		set("trackstatus03", trackstatus03);
	}

	public java.lang.Integer getTrackstatus03() {
		return get("trackstatus03");
	}

	public void setSerror03(java.lang.String serror03) {
		set("serror03", serror03);
	}

	public java.lang.String getSerror03() {
		return get("serror03");
	}

	public void setMingcheng04(java.lang.String mingcheng04) {
		set("mingcheng04", mingcheng04);
	}

	public java.lang.String getMingcheng04() {
		return get("mingcheng04");
	}

	public void setSprice04(java.lang.String sprice04) {
		set("sprice04", sprice04);
	}

	public java.lang.String getSprice04() {
		return get("sprice04");
	}

	public void setHavenow04(java.lang.Integer havenow04) {
		set("havenow04", havenow04);
	}

	public java.lang.Integer getHavenow04() {
		return get("havenow04");
	}

	public void setNow04(java.lang.Integer now04) {
		set("now04", now04);
	}

	public java.lang.Integer getNow04() {
		return get("now04");
	}

	public void setMax04(java.lang.Integer max04) {
		set("max04", max04);
	}

	public java.lang.Integer getMax04() {
		return get("max04");
	}

	public void setTrackstatus04(java.lang.Integer trackstatus04) {
		set("trackstatus04", trackstatus04);
	}

	public java.lang.Integer getTrackstatus04() {
		return get("trackstatus04");
	}

	public void setSerror04(java.lang.String serror04) {
		set("serror04", serror04);
	}

	public java.lang.String getSerror04() {
		return get("serror04");
	}

	public void setMingcheng05(java.lang.String mingcheng05) {
		set("mingcheng05", mingcheng05);
	}

	public java.lang.String getMingcheng05() {
		return get("mingcheng05");
	}

	public void setSprice05(java.lang.String sprice05) {
		set("sprice05", sprice05);
	}

	public java.lang.String getSprice05() {
		return get("sprice05");
	}

	public void setHavenow05(java.lang.Integer havenow05) {
		set("havenow05", havenow05);
	}

	public java.lang.Integer getHavenow05() {
		return get("havenow05");
	}

	public void setNow05(java.lang.Integer now05) {
		set("now05", now05);
	}

	public java.lang.Integer getNow05() {
		return get("now05");
	}

	public void setMax05(java.lang.Integer max05) {
		set("max05", max05);
	}

	public java.lang.Integer getMax05() {
		return get("max05");
	}

	public void setTrackstatus05(java.lang.Integer trackstatus05) {
		set("trackstatus05", trackstatus05);
	}

	public java.lang.Integer getTrackstatus05() {
		return get("trackstatus05");
	}

	public void setSerror05(java.lang.String serror05) {
		set("serror05", serror05);
	}

	public java.lang.String getSerror05() {
		return get("serror05");
	}

	public void setMingcheng06(java.lang.String mingcheng06) {
		set("mingcheng06", mingcheng06);
	}

	public java.lang.String getMingcheng06() {
		return get("mingcheng06");
	}

	public void setSprice06(java.lang.String sprice06) {
		set("sprice06", sprice06);
	}

	public java.lang.String getSprice06() {
		return get("sprice06");
	}

	public void setHavenow06(java.lang.Integer havenow06) {
		set("havenow06", havenow06);
	}

	public java.lang.Integer getHavenow06() {
		return get("havenow06");
	}

	public void setNow06(java.lang.Integer now06) {
		set("now06", now06);
	}

	public java.lang.Integer getNow06() {
		return get("now06");
	}

	public void setMax06(java.lang.Integer max06) {
		set("max06", max06);
	}

	public java.lang.Integer getMax06() {
		return get("max06");
	}

	public void setTrackstatus06(java.lang.Integer trackstatus06) {
		set("trackstatus06", trackstatus06);
	}

	public java.lang.Integer getTrackstatus06() {
		return get("trackstatus06");
	}

	public void setSerror06(java.lang.String serror06) {
		set("serror06", serror06);
	}

	public java.lang.String getSerror06() {
		return get("serror06");
	}

	public void setMingcheng07(java.lang.String mingcheng07) {
		set("mingcheng07", mingcheng07);
	}

	public java.lang.String getMingcheng07() {
		return get("mingcheng07");
	}

	public void setSprice07(java.lang.String sprice07) {
		set("sprice07", sprice07);
	}

	public java.lang.String getSprice07() {
		return get("sprice07");
	}

	public void setHavenow07(java.lang.Integer havenow07) {
		set("havenow07", havenow07);
	}

	public java.lang.Integer getHavenow07() {
		return get("havenow07");
	}

	public void setNow07(java.lang.Integer now07) {
		set("now07", now07);
	}

	public java.lang.Integer getNow07() {
		return get("now07");
	}

	public void setMax07(java.lang.Integer max07) {
		set("max07", max07);
	}

	public java.lang.Integer getMax07() {
		return get("max07");
	}

	public void setTrackstatus07(java.lang.Integer trackstatus07) {
		set("trackstatus07", trackstatus07);
	}

	public java.lang.Integer getTrackstatus07() {
		return get("trackstatus07");
	}

	public void setSerror07(java.lang.String serror07) {
		set("serror07", serror07);
	}

	public java.lang.String getSerror07() {
		return get("serror07");
	}

	public void setMingcheng08(java.lang.String mingcheng08) {
		set("mingcheng08", mingcheng08);
	}

	public java.lang.String getMingcheng08() {
		return get("mingcheng08");
	}

	public void setSprice08(java.lang.String sprice08) {
		set("sprice08", sprice08);
	}

	public java.lang.String getSprice08() {
		return get("sprice08");
	}

	public void setHavenow08(java.lang.Integer havenow08) {
		set("havenow08", havenow08);
	}

	public java.lang.Integer getHavenow08() {
		return get("havenow08");
	}

	public void setNow08(java.lang.Integer now08) {
		set("now08", now08);
	}

	public java.lang.Integer getNow08() {
		return get("now08");
	}

	public void setMax08(java.lang.Integer max08) {
		set("max08", max08);
	}

	public java.lang.Integer getMax08() {
		return get("max08");
	}

	public void setTrackstatus08(java.lang.Integer trackstatus08) {
		set("trackstatus08", trackstatus08);
	}

	public java.lang.Integer getTrackstatus08() {
		return get("trackstatus08");
	}

	public void setSerror08(java.lang.String serror08) {
		set("serror08", serror08);
	}

	public java.lang.String getSerror08() {
		return get("serror08");
	}

	public void setMingcheng09(java.lang.String mingcheng09) {
		set("mingcheng09", mingcheng09);
	}

	public java.lang.String getMingcheng09() {
		return get("mingcheng09");
	}

	public void setSprice09(java.lang.String sprice09) {
		set("sprice09", sprice09);
	}

	public java.lang.String getSprice09() {
		return get("sprice09");
	}

	public void setHavenow09(java.lang.Integer havenow09) {
		set("havenow09", havenow09);
	}

	public java.lang.Integer getHavenow09() {
		return get("havenow09");
	}

	public void setNow09(java.lang.Integer now09) {
		set("now09", now09);
	}

	public java.lang.Integer getNow09() {
		return get("now09");
	}

	public void setMax09(java.lang.Integer max09) {
		set("max09", max09);
	}

	public java.lang.Integer getMax09() {
		return get("max09");
	}

	public void setTrackstatus09(java.lang.Integer trackstatus09) {
		set("trackstatus09", trackstatus09);
	}

	public java.lang.Integer getTrackstatus09() {
		return get("trackstatus09");
	}

	public void setSerror09(java.lang.String serror09) {
		set("serror09", serror09);
	}

	public java.lang.String getSerror09() {
		return get("serror09");
	}

	public void setMingcheng10(java.lang.String mingcheng10) {
		set("mingcheng10", mingcheng10);
	}

	public java.lang.String getMingcheng10() {
		return get("mingcheng10");
	}

	public void setSprice10(java.lang.String sprice10) {
		set("sprice10", sprice10);
	}

	public java.lang.String getSprice10() {
		return get("sprice10");
	}

	public void setHavenow10(java.lang.Integer havenow10) {
		set("havenow10", havenow10);
	}

	public java.lang.Integer getHavenow10() {
		return get("havenow10");
	}

	public void setNow10(java.lang.Integer now10) {
		set("now10", now10);
	}

	public java.lang.Integer getNow10() {
		return get("now10");
	}

	public void setMax10(java.lang.Integer max10) {
		set("max10", max10);
	}

	public java.lang.Integer getMax10() {
		return get("max10");
	}

	public void setTrackstatus10(java.lang.Integer trackstatus10) {
		set("trackstatus10", trackstatus10);
	}

	public java.lang.Integer getTrackstatus10() {
		return get("trackstatus10");
	}

	public void setSerror10(java.lang.String serror10) {
		set("serror10", serror10);
	}

	public java.lang.String getSerror10() {
		return get("serror10");
	}

	public void setMingcheng11(java.lang.String mingcheng11) {
		set("mingcheng11", mingcheng11);
	}

	public java.lang.String getMingcheng11() {
		return get("mingcheng11");
	}

	public void setSprice11(java.lang.String sprice11) {
		set("sprice11", sprice11);
	}

	public java.lang.String getSprice11() {
		return get("sprice11");
	}

	public void setHavenow11(java.lang.Integer havenow11) {
		set("havenow11", havenow11);
	}

	public java.lang.Integer getHavenow11() {
		return get("havenow11");
	}

	public void setNow11(java.lang.Integer now11) {
		set("now11", now11);
	}

	public java.lang.Integer getNow11() {
		return get("now11");
	}

	public void setMax11(java.lang.Integer max11) {
		set("max11", max11);
	}

	public java.lang.Integer getMax11() {
		return get("max11");
	}

	public void setTrackstatus11(java.lang.Integer trackstatus11) {
		set("trackstatus11", trackstatus11);
	}

	public java.lang.Integer getTrackstatus11() {
		return get("trackstatus11");
	}

	public void setSerror11(java.lang.String serror11) {
		set("serror11", serror11);
	}

	public java.lang.String getSerror11() {
		return get("serror11");
	}

	public void setMingcheng12(java.lang.String mingcheng12) {
		set("mingcheng12", mingcheng12);
	}

	public java.lang.String getMingcheng12() {
		return get("mingcheng12");
	}

	public void setSprice12(java.lang.String sprice12) {
		set("sprice12", sprice12);
	}

	public java.lang.String getSprice12() {
		return get("sprice12");
	}

	public void setHavenow12(java.lang.Integer havenow12) {
		set("havenow12", havenow12);
	}

	public java.lang.Integer getHavenow12() {
		return get("havenow12");
	}

	public void setNow12(java.lang.Integer now12) {
		set("now12", now12);
	}

	public java.lang.Integer getNow12() {
		return get("now12");
	}

	public void setMax12(java.lang.Integer max12) {
		set("max12", max12);
	}

	public java.lang.Integer getMax12() {
		return get("max12");
	}

	public void setTrackstatus12(java.lang.Integer trackstatus12) {
		set("trackstatus12", trackstatus12);
	}

	public java.lang.Integer getTrackstatus12() {
		return get("trackstatus12");
	}

	public void setSerror12(java.lang.String serror12) {
		set("serror12", serror12);
	}

	public java.lang.String getSerror12() {
		return get("serror12");
	}

	public void setMingcheng13(java.lang.String mingcheng13) {
		set("mingcheng13", mingcheng13);
	}

	public java.lang.String getMingcheng13() {
		return get("mingcheng13");
	}

	public void setSprice13(java.lang.String sprice13) {
		set("sprice13", sprice13);
	}

	public java.lang.String getSprice13() {
		return get("sprice13");
	}

	public void setHavenow13(java.lang.Integer havenow13) {
		set("havenow13", havenow13);
	}

	public java.lang.Integer getHavenow13() {
		return get("havenow13");
	}

	public void setNow13(java.lang.Integer now13) {
		set("now13", now13);
	}

	public java.lang.Integer getNow13() {
		return get("now13");
	}

	public void setMax13(java.lang.Integer max13) {
		set("max13", max13);
	}

	public java.lang.Integer getMax13() {
		return get("max13");
	}

	public void setTrackstatus13(java.lang.Integer trackstatus13) {
		set("trackstatus13", trackstatus13);
	}

	public java.lang.Integer getTrackstatus13() {
		return get("trackstatus13");
	}

	public void setSerror13(java.lang.String serror13) {
		set("serror13", serror13);
	}

	public java.lang.String getSerror13() {
		return get("serror13");
	}

	public void setMingcheng14(java.lang.String mingcheng14) {
		set("mingcheng14", mingcheng14);
	}

	public java.lang.String getMingcheng14() {
		return get("mingcheng14");
	}

	public void setSprice14(java.lang.String sprice14) {
		set("sprice14", sprice14);
	}

	public java.lang.String getSprice14() {
		return get("sprice14");
	}

	public void setHavenow14(java.lang.Integer havenow14) {
		set("havenow14", havenow14);
	}

	public java.lang.Integer getHavenow14() {
		return get("havenow14");
	}

	public void setNow14(java.lang.Integer now14) {
		set("now14", now14);
	}

	public java.lang.Integer getNow14() {
		return get("now14");
	}

	public void setMax14(java.lang.Integer max14) {
		set("max14", max14);
	}

	public java.lang.Integer getMax14() {
		return get("max14");
	}

	public void setTrackstatus14(java.lang.Integer trackstatus14) {
		set("trackstatus14", trackstatus14);
	}

	public java.lang.Integer getTrackstatus14() {
		return get("trackstatus14");
	}

	public void setSerror14(java.lang.String serror14) {
		set("serror14", serror14);
	}

	public java.lang.String getSerror14() {
		return get("serror14");
	}

	public void setMingcheng15(java.lang.String mingcheng15) {
		set("mingcheng15", mingcheng15);
	}

	public java.lang.String getMingcheng15() {
		return get("mingcheng15");
	}

	public void setSprice15(java.lang.String sprice15) {
		set("sprice15", sprice15);
	}

	public java.lang.String getSprice15() {
		return get("sprice15");
	}

	public void setHavenow15(java.lang.Integer havenow15) {
		set("havenow15", havenow15);
	}

	public java.lang.Integer getHavenow15() {
		return get("havenow15");
	}

	public void setNow15(java.lang.Integer now15) {
		set("now15", now15);
	}

	public java.lang.Integer getNow15() {
		return get("now15");
	}

	public void setMax15(java.lang.Integer max15) {
		set("max15", max15);
	}

	public java.lang.Integer getMax15() {
		return get("max15");
	}

	public void setTrackstatus15(java.lang.Integer trackstatus15) {
		set("trackstatus15", trackstatus15);
	}

	public java.lang.Integer getTrackstatus15() {
		return get("trackstatus15");
	}

	public void setSerror15(java.lang.String serror15) {
		set("serror15", serror15);
	}

	public java.lang.String getSerror15() {
		return get("serror15");
	}

	public void setMingcheng16(java.lang.String mingcheng16) {
		set("mingcheng16", mingcheng16);
	}

	public java.lang.String getMingcheng16() {
		return get("mingcheng16");
	}

	public void setSprice16(java.lang.String sprice16) {
		set("sprice16", sprice16);
	}

	public java.lang.String getSprice16() {
		return get("sprice16");
	}

	public void setHavenow16(java.lang.Integer havenow16) {
		set("havenow16", havenow16);
	}

	public java.lang.Integer getHavenow16() {
		return get("havenow16");
	}

	public void setNow16(java.lang.Integer now16) {
		set("now16", now16);
	}

	public java.lang.Integer getNow16() {
		return get("now16");
	}

	public void setMax16(java.lang.Integer max16) {
		set("max16", max16);
	}

	public java.lang.Integer getMax16() {
		return get("max16");
	}

	public void setTrackstatus16(java.lang.Integer trackstatus16) {
		set("trackstatus16", trackstatus16);
	}

	public java.lang.Integer getTrackstatus16() {
		return get("trackstatus16");
	}

	public void setSerror16(java.lang.String serror16) {
		set("serror16", serror16);
	}

	public java.lang.String getSerror16() {
		return get("serror16");
	}

	public void setMingcheng17(java.lang.String mingcheng17) {
		set("mingcheng17", mingcheng17);
	}

	public java.lang.String getMingcheng17() {
		return get("mingcheng17");
	}

	public void setSprice17(java.lang.String sprice17) {
		set("sprice17", sprice17);
	}

	public java.lang.String getSprice17() {
		return get("sprice17");
	}

	public void setHavenow17(java.lang.Integer havenow17) {
		set("havenow17", havenow17);
	}

	public java.lang.Integer getHavenow17() {
		return get("havenow17");
	}

	public void setNow17(java.lang.Integer now17) {
		set("now17", now17);
	}

	public java.lang.Integer getNow17() {
		return get("now17");
	}

	public void setMax17(java.lang.Integer max17) {
		set("max17", max17);
	}

	public java.lang.Integer getMax17() {
		return get("max17");
	}

	public void setTrackstatus17(java.lang.Integer trackstatus17) {
		set("trackstatus17", trackstatus17);
	}

	public java.lang.Integer getTrackstatus17() {
		return get("trackstatus17");
	}

	public void setSerror17(java.lang.String serror17) {
		set("serror17", serror17);
	}

	public java.lang.String getSerror17() {
		return get("serror17");
	}

	public void setMingcheng18(java.lang.String mingcheng18) {
		set("mingcheng18", mingcheng18);
	}

	public java.lang.String getMingcheng18() {
		return get("mingcheng18");
	}

	public void setSprice18(java.lang.String sprice18) {
		set("sprice18", sprice18);
	}

	public java.lang.String getSprice18() {
		return get("sprice18");
	}

	public void setHavenow18(java.lang.Integer havenow18) {
		set("havenow18", havenow18);
	}

	public java.lang.Integer getHavenow18() {
		return get("havenow18");
	}

	public void setNow18(java.lang.Integer now18) {
		set("now18", now18);
	}

	public java.lang.Integer getNow18() {
		return get("now18");
	}

	public void setMax18(java.lang.Integer max18) {
		set("max18", max18);
	}

	public java.lang.Integer getMax18() {
		return get("max18");
	}

	public void setTrackstatus18(java.lang.Integer trackstatus18) {
		set("trackstatus18", trackstatus18);
	}

	public java.lang.Integer getTrackstatus18() {
		return get("trackstatus18");
	}

	public void setSerror18(java.lang.String serror18) {
		set("serror18", serror18);
	}

	public java.lang.String getSerror18() {
		return get("serror18");
	}

	public void setMingcheng19(java.lang.String mingcheng19) {
		set("mingcheng19", mingcheng19);
	}

	public java.lang.String getMingcheng19() {
		return get("mingcheng19");
	}

	public void setSprice19(java.lang.String sprice19) {
		set("sprice19", sprice19);
	}

	public java.lang.String getSprice19() {
		return get("sprice19");
	}

	public void setHavenow19(java.lang.Integer havenow19) {
		set("havenow19", havenow19);
	}

	public java.lang.Integer getHavenow19() {
		return get("havenow19");
	}

	public void setNow19(java.lang.Integer now19) {
		set("now19", now19);
	}

	public java.lang.Integer getNow19() {
		return get("now19");
	}

	public void setMax19(java.lang.Integer max19) {
		set("max19", max19);
	}

	public java.lang.Integer getMax19() {
		return get("max19");
	}

	public void setTrackstatus19(java.lang.Integer trackstatus19) {
		set("trackstatus19", trackstatus19);
	}

	public java.lang.Integer getTrackstatus19() {
		return get("trackstatus19");
	}

	public void setSerror19(java.lang.String serror19) {
		set("serror19", serror19);
	}

	public java.lang.String getSerror19() {
		return get("serror19");
	}

	public void setMingcheng20(java.lang.String mingcheng20) {
		set("mingcheng20", mingcheng20);
	}

	public java.lang.String getMingcheng20() {
		return get("mingcheng20");
	}

	public void setSprice20(java.lang.String sprice20) {
		set("sprice20", sprice20);
	}

	public java.lang.String getSprice20() {
		return get("sprice20");
	}

	public void setHavenow20(java.lang.Integer havenow20) {
		set("havenow20", havenow20);
	}

	public java.lang.Integer getHavenow20() {
		return get("havenow20");
	}

	public void setNow20(java.lang.Integer now20) {
		set("now20", now20);
	}

	public java.lang.Integer getNow20() {
		return get("now20");
	}

	public void setMax20(java.lang.Integer max20) {
		set("max20", max20);
	}

	public java.lang.Integer getMax20() {
		return get("max20");
	}

	public void setTrackstatus20(java.lang.Integer trackstatus20) {
		set("trackstatus20", trackstatus20);
	}

	public java.lang.Integer getTrackstatus20() {
		return get("trackstatus20");
	}

	public void setSerror20(java.lang.String serror20) {
		set("serror20", serror20);
	}

	public java.lang.String getSerror20() {
		return get("serror20");
	}

	public void setMingcheng21(java.lang.String mingcheng21) {
		set("mingcheng21", mingcheng21);
	}

	public java.lang.String getMingcheng21() {
		return get("mingcheng21");
	}

	public void setSprice21(java.lang.String sprice21) {
		set("sprice21", sprice21);
	}

	public java.lang.String getSprice21() {
		return get("sprice21");
	}

	public void setHavenow21(java.lang.Integer havenow21) {
		set("havenow21", havenow21);
	}

	public java.lang.Integer getHavenow21() {
		return get("havenow21");
	}

	public void setNow21(java.lang.Integer now21) {
		set("now21", now21);
	}

	public java.lang.Integer getNow21() {
		return get("now21");
	}

	public void setMax21(java.lang.Integer max21) {
		set("max21", max21);
	}

	public java.lang.Integer getMax21() {
		return get("max21");
	}

	public void setTrackstatus21(java.lang.Integer trackstatus21) {
		set("trackstatus21", trackstatus21);
	}

	public java.lang.Integer getTrackstatus21() {
		return get("trackstatus21");
	}

	public void setSerror21(java.lang.String serror21) {
		set("serror21", serror21);
	}

	public java.lang.String getSerror21() {
		return get("serror21");
	}

	public void setWeixinpara(java.lang.String weixinpara) {
		set("weixinpara", weixinpara);
	}

	public java.lang.String getWeixinpara() {
		return get("weixinpara");
	}

	public void setAlipaypara(java.lang.String alipaypara) {
		set("alipaypara", alipaypara);
	}

	public java.lang.String getAlipaypara() {
		return get("alipaypara");
	}

	public void setIccardname(java.lang.String iccardname) {
		set("iccardname", iccardname);
	}

	public java.lang.String getIccardname() {
		return get("iccardname");
	}

	public void setUpdatetime(java.util.Date updatetime) {
		set("updatetime", updatetime);
	}

	public java.util.Date getUpdatetime() {
		return get("updatetime");
	}

	public void setPlace(java.lang.String place) {
		set("place", place);
	}

	public java.lang.String getPlace() {
		return get("place");
	}

	public void setLongitude(java.lang.Double longitude) {
		set("longitude", longitude);
	}

	public java.lang.Double getLongitude() {
		return get("longitude");
	}

	public void setLatitude(java.lang.Double latitude) {
		set("latitude", latitude);
	}

	public java.lang.Double getLatitude() {
		return get("latitude");
	}

	public void setHzcitydiscount(java.lang.Integer hzcitydiscount) {
		set("hzcitydiscount", hzcitydiscount);
	}

	public java.lang.Integer getHzcitydiscount() {
		return get("hzcitydiscount");
	}

	public void setZajiid(java.lang.String zajiid) {
		set("zajiid", zajiid);
	}

	public java.lang.String getZajiid() {
		return get("zajiid");
	}

	public void setPosid(java.lang.String posid) {
		set("posid", posid);
	}

	public java.lang.String getPosid() {
		return get("posid");
	}

}
