package com.jfinal.weixin.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseRolePermMst<M extends BaseRolePermMst<M>> extends Model<M> implements IBean {

	public void setIdRole(java.math.BigInteger idRole) {
		set("id_role", idRole);
	}

	public java.math.BigInteger getIdRole() {
		return get("id_role");
	}

	public void setIdModule(java.math.BigInteger idModule) {
		set("id_module", idModule);
	}

	public java.math.BigInteger getIdModule() {
		return get("id_module");
	}

	public void setFlgView(java.lang.Integer flgView) {
		set("flg_view", flgView);
	}

	public java.lang.Integer getFlgView() {
		return get("flg_view");
	}

	public void setFlgAdd(java.lang.Integer flgAdd) {
		set("flg_add", flgAdd);
	}

	public java.lang.Integer getFlgAdd() {
		return get("flg_add");
	}

	public void setFlgEdit(java.lang.Integer flgEdit) {
		set("flg_edit", flgEdit);
	}

	public java.lang.Integer getFlgEdit() {
		return get("flg_edit");
	}

	public void setFlgDel(java.lang.Integer flgDel) {
		set("flg_del", flgDel);
	}

	public java.lang.Integer getFlgDel() {
		return get("flg_del");
	}

	public void setFlgChk(java.lang.Integer flgChk) {
		set("flg_chk", flgChk);
	}

	public java.lang.Integer getFlgChk() {
		return get("flg_chk");
	}

	public void setFlgPrint(java.lang.Integer flgPrint) {
		set("flg_print", flgPrint);
	}

	public java.lang.Integer getFlgPrint() {
		return get("flg_print");
	}

	public void setFlgExport(java.lang.Integer flgExport) {
		set("flg_export", flgExport);
	}

	public java.lang.Integer getFlgExport() {
		return get("flg_export");
	}

	public void setFlgImport(java.lang.Integer flgImport) {
		set("flg_import", flgImport);
	}

	public java.lang.Integer getFlgImport() {
		return get("flg_import");
	}

	public void setIdCrtUser(java.math.BigInteger idCrtUser) {
		set("id_crt_user", idCrtUser);
	}

	public java.math.BigInteger getIdCrtUser() {
		return get("id_crt_user");
	}

	public void setTimeCrt(java.util.Date timeCrt) {
		set("time_crt", timeCrt);
	}

	public java.util.Date getTimeCrt() {
		return get("time_crt");
	}

	public void setIdUpdUser(java.math.BigInteger idUpdUser) {
		set("id_upd_user", idUpdUser);
	}

	public java.math.BigInteger getIdUpdUser() {
		return get("id_upd_user");
	}

	public void setTimeUpd(java.util.Date timeUpd) {
		set("time_upd", timeUpd);
	}

	public java.util.Date getTimeUpd() {
		return get("time_upd");
	}

}
