package com.jfinal.weixin.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseAbSend<M extends BaseAbSend<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public void setPhns(java.lang.String phns) {
		set("phns", phns);
	}

	public java.lang.String getPhns() {
		return get("phns");
	}

	public void setCont(java.lang.String cont) {
		set("cont", cont);
	}

	public java.lang.String getCont() {
		return get("cont");
	}

	public void setTim(java.lang.String tim) {
		set("tim", tim);
	}

	public java.lang.String getTim() {
		return get("tim");
	}

	public void setFlag(java.lang.Integer flag) {
		set("flag", flag);
	}

	public java.lang.Integer getFlag() {
		return get("flag");
	}

}
