package com.jfinal.weixin.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseSupply206<M extends BaseSupply206<M>> extends Model<M> implements IBean {

	public void setDeviceid(java.lang.String deviceid) {
		set("deviceid", deviceid);
	}

	public java.lang.String getDeviceid() {
		return get("deviceid");
	}

	public void setInserttime(java.util.Date inserttime) {
		set("inserttime", inserttime);
	}

	public java.util.Date getInserttime() {
		return get("inserttime");
	}

	public void setCashcount(java.lang.Integer cashcount) {
		set("cashcount", cashcount);
	}

	public java.lang.Integer getCashcount() {
		return get("cashcount");
	}

	public void setCashmoney(java.lang.String cashmoney) {
		set("cashmoney", cashmoney);
	}

	public java.lang.String getCashmoney() {
		return get("cashmoney");
	}

	public void setAlipaycount(java.lang.Integer alipaycount) {
		set("alipaycount", alipaycount);
	}

	public java.lang.Integer getAlipaycount() {
		return get("alipaycount");
	}

	public void setAlipaymoney(java.lang.String alipaymoney) {
		set("alipaymoney", alipaymoney);
	}

	public java.lang.String getAlipaymoney() {
		return get("alipaymoney");
	}

	public void setWeixincount(java.lang.Integer weixincount) {
		set("weixincount", weixincount);
	}

	public java.lang.Integer getWeixincount() {
		return get("weixincount");
	}

	public void setWeixinmoney(java.lang.String weixinmoney) {
		set("weixinmoney", weixinmoney);
	}

	public java.lang.String getWeixinmoney() {
		return get("weixinmoney");
	}

	public void setTotalcount(java.lang.Integer totalcount) {
		set("totalcount", totalcount);
	}

	public java.lang.Integer getTotalcount() {
		return get("totalcount");
	}

	public void setTotalmoney(java.lang.String totalmoney) {
		set("totalmoney", totalmoney);
	}

	public java.lang.String getTotalmoney() {
		return get("totalmoney");
	}

}
