package com.jfinal.weixin.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseIdVmoperatecard<M extends BaseIdVmoperatecard<M>> extends Model<M> implements IBean {

	public void setOperateid(java.lang.Long operateid) {
		set("operateid", operateid);
	}

	public java.lang.Long getOperateid() {
		return get("operateid");
	}

	public void setAddtime(java.util.Date addtime) {
		set("addtime", addtime);
	}

	public java.util.Date getAddtime() {
		return get("addtime");
	}

	public void setCardsid(java.lang.Long cardsid) {
		set("cardsid", cardsid);
	}

	public java.lang.Long getCardsid() {
		return get("cardsid");
	}

	public void setOrgstatus(java.lang.Integer orgstatus) {
		set("orgstatus", orgstatus);
	}

	public java.lang.Integer getOrgstatus() {
		return get("orgstatus");
	}

	public void setStatus(java.lang.Integer status) {
		set("status", status);
	}

	public java.lang.Integer getStatus() {
		return get("status");
	}

	public void setUpdaterealname(java.lang.String updaterealname) {
		set("updaterealname", updaterealname);
	}

	public java.lang.String getUpdaterealname() {
		return get("updaterealname");
	}

}
