package com.jfinal.weixin.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseAppPointruler<M extends BaseAppPointruler<M>> extends Model<M> implements IBean {

	public void setItems(java.lang.String items) {
		set("items", items);
	}

	public java.lang.String getItems() {
		return get("items");
	}

	public void setPoint(java.lang.Integer point) {
		set("point", point);
	}

	public java.lang.Integer getPoint() {
		return get("point");
	}

}
