package com.jfinal.weixin.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseAbRecv<M extends BaseAbRecv<M>> extends Model<M> implements IBean {

	public void setPhn(java.lang.String phn) {
		set("phn", phn);
	}

	public java.lang.String getPhn() {
		return get("phn");
	}

	public void setCont(java.lang.String cont) {
		set("cont", cont);
	}

	public java.lang.String getCont() {
		return get("cont");
	}

	public void setTim(java.lang.String tim) {
		set("tim", tim);
	}

	public java.lang.String getTim() {
		return get("tim");
	}

}
