package com.jfinal.weixin.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseHzcityyyyymmdd<M extends BaseHzcityyyyymmdd<M>> extends Model<M> implements IBean {

	public void setYyyymmdd(java.lang.String yyyymmdd) {
		set("yyyymmdd", yyyymmdd);
	}

	public java.lang.String getYyyymmdd() {
		return get("yyyymmdd");
	}

	public void setInserttime(java.util.Date inserttime) {
		set("inserttime", inserttime);
	}

	public java.util.Date getInserttime() {
		return get("inserttime");
	}

}
